/** Editorial alternatives, never displayed until Jev selects and validates against a passage. */
export const sentenceCandidates:Record<string,string[]>={
 business:[
  'Sells ads across Search, YouTube and partner sites, mostly to advertisers.',
  'Sells advertising across its online services.',
  'Provides cloud infrastructure, databases and enterprise software to businesses.',
  'Designs graphics processors and computing platforms for businesses and consumers.',
  'Provides advertising tools to advertisers, agencies and publishers.',
  'Sells phones, computers, tablets and related services to consumers and businesses.',
  'Sells drinks and beverage concentrates through bottlers and retailers.',
  'Sells athletic clothing and accessories directly to customers.',
  'Provides software, information and services that help professionals do their work.',
  'Provides financial services to small businesses and individuals.',
  'Provides banking, lending and investment services to consumers and businesses.',
  'Lends to businesses and individuals, with loans secured against assets.',
  'Makes and sells vehicles, and helps customers finance them.',
  'Makes and sells luxury sports cars worldwide.',
  'Operates energy, retail and telecommunications businesses.',
 ],
 moat:['Its brand is widely recognised.', 'Its brands have strong consumer recognition and loyalty.', 'Customers trust its brands.', 'Its distinctive brand attracts customers.','Changing providers would disrupt customers’ work.','More users make the service more useful.','Its distribution network helps it reach customers.','Its scale lowers costs.', 'Its trusted brands offer specialised content.'],
 pricing:['Higher prices have held up alongside demand.','Higher prices have reduced demand.'],
 concentration:['Sales are spread across customers.','The business relies on a small group of suppliers.','A small group of customers accounts for substantial sales.'],
 allocation:['Repurchases its own shares.','Has paid dividends to shareholders.','Management buys businesses to expand.','Invests in new products and selected acquisitions.'],
 candor:['Some non-recurring revenues declined.','Management acknowledges a decline in profits.','Management acknowledges problems with earlier decisions.'],
 competitors:['It competes with other large technology companies.','It competes with other beverage brands.','It competes with other sportswear brands.'],
 risk:['New technology could weaken demand for its services.','Supply disruptions could prevent it from meeting demand.','Competitors could innovate faster or deliver products more cheaply.', 'Imitation products could compete with its own.', 'Online shopping could put downward pressure on prices.','Damage to its reputation could weaken demand.','Regulatory changes could restrict its business.','Cyberattacks could disrupt its operations.'],
 flags:['Capital spending exceeds depreciation.','Capital spending exceeds depreciation and has been rising.','Cash exceeds debt.','Receivables are growing faster than sales.','Inventory is growing faster than sales.','Goodwill exceeds shareholders’ equity.','Adjusted profit excludes costs that leave a reported loss.','Guarantees expose it to another company’s obligations.','Credit backstops expose it to another company’s obligations.','It relies on a small group of suppliers.','A major customer accounts for substantial sales.'],
};
/** Additional, distinct operating facts; used only to fill remaining overview space. */
export const detailCandidates=[
 'Offers cloud infrastructure and collaboration tools to businesses.',
 'Sells apps and digital content through Google Play.',
 'Offers subscription services including YouTube Premium.',
 'Produces consumer devices.',
 'Uses AI in its advertising products.',
 'Offers streaming, gaming and subscription services.',
 'Sells wearables and accessories alongside its main devices.',
 'Distributes third-party apps through the App Store.',
 'Provides payment services.',
 'Sells through its own stores and third-party distributors.',
 'Owns and markets multiple beverage brands.',
 'Supplies concentrates and syrups to bottlers.',
 'Sells sparkling drinks, water, coffee, tea and juices.',
 'Its brands include Coca-Cola and Sprite.',
 'Designs clothing for yoga, running and training.',
 'Offers footwear as well as clothing.',
 'Sells through stores and its online channels.',
 'Targets both women and men.',
 'Uses third-party manufacturers to make its products.',
 'Serves legal, tax, accounting and healthcare professionals.',
 'Supplies software for compliance and risk management.',
 'Provides expert information for professional decisions.',
 'Accepts deposits and provides consumer loans.',
 'Issues credit cards and processes payments.',
 'Provides investment banking and capital-raising services.',
 'Manages investments for institutions and wealthy clients.',
 'Offers mortgages and vehicle financing.',
 'Finances equipment and other business assets.',
 'Provides loans for residential property development.',
 'Finances used cars and other vehicles.',
 'Offers savings products to individuals and companies.',
 'Provides invoice financing to businesses.',
 'Makes passenger cars and commercial vehicles.',
 'Provides finance and leasing for vehicle buyers.',
 'Offers spare parts and vehicle-related services.',
 'Operates through vehicle and financial services businesses.',
 'Develops hybrid and electric vehicles.',
 'Refines petroleum and produces petrochemicals.',
 'Explores for and produces oil and gas.',
 'Runs retail stores and digital services.',
 'Invests in renewable energy.',
 'Operates telecommunications services through Jio.',
 'Sells sports cars, supercars and track cars.',
 'Provides spare parts, maintenance and restoration services.',
 'Licenses its brand for luxury and lifestyle goods.',
 'Operates museums and branded attractions.',
 'Provides financing and leasing services.',
];
