'use client';
import {useState} from 'react';
import {SidePanel} from './SidePanel';
import {PanelTabs} from './PanelTabs';
import {ValueLink} from './ValueLink';
export function MethodSummary({author}:{author?:string}) {
 return <PanelTabs tabs={[
  {label:'Quality',content:<><h3>A good business, at a sensible price.</h3><p>Five tests check stability, competitive advantage, cash generation, capital allocation and honest accounting.</p><dl className="panel-numbers"><div><dt>History</dt><dd>10 years</dd></div><div><dt>Quality</dt><dd>5 tests</dd></div><div><dt>Safety discount</dt><dd>25–50%</dd></div></dl><p>All five must pass. The share price must also leave room for error and the expected return must meet the required return.</p></>},
  {label:'Value',content:<><h3>Future owner cash, in today’s money.</h3><p>We project normalised owner earnings for ten years, discount future cash, add net cash and divide by shares. Banks and insurers use tangible book value and returns on equity.</p><dl className="panel-numbers"><div><dt>Growth cap</dt><dd>8%</dd></div><div><dt>Long-run growth</dt><dd>3%</dd></div><div><dt>Return floor</dt><dd>10%</dd></div></dl><p>Required return is the higher of 10% or the local ten-year government bond yield plus four percentage points. Expected yearly return is cash yield plus capped growth; it is an estimate, not a guarantee.</p></>},
  {label:'View',content:<><h3>Buy now. Next closest. The rest.</h3><p>Buy now ranks qualifying companies by expected yearly return. In past years, it ranks them by subsequent price gain. Only the first non-negative pick gets a strong green fill.</p><p>Next closest shows companies up to 50% above their buy price on one linear scale. A company below its buy price can still miss the return hurdle; its return is shown beside it.</p><p>The rest groups more expensive companies, with the largest company logos first. Companies without a comparable valuation remain in All companies.</p><p>Market access, company sizes and investor holdings use today’s listings.</p></>},
  {label:'History',content:<><h3>Historical snapshots, with limits.</h3><p>Each company needs ten fiscal years and a price after that year’s filing. Early years cover fewer companies; the timeline starts at 300.</p><p>Returns are cumulative price gains to the latest quote, excluding dividends, fees and taxes. The simulation compares the selected buy cohort’s median with all covered companies that year.</p><p>Restated financials, missing delistings, today’s currencies and required returns can flatter results. History uses numerical tests without AI report readings. It is not an investable backtest.</p></>},
  {label:'Sources',content:<><h3>Filings and market data.</h3><p>SEC, EDINET and ESEF filings; EODHD fundamentals; Yahoo monthly prices. Logos use provider images or official-site icons.</p><p>Estimates use share counts from independent sources.</p><p>These are independent rules inspired by Buffett, not his recommendations. Errors, debt and currency changes can materially change an estimate.</p>{author&&<p>By {author}</p>}<ValueLink href="/method">Full method & sources ↗</ValueLink></>},
 ]}/>;
}
export function AboutMethod({author}:{author?:string}){
 const [open,setOpen]=useState(false);return <><button className="about-method" onClick={()=>setOpen(true)}>Method</button>{open&&<SidePanel title="Method" onClose={()=>setOpen(false)}><MethodSummary author={author}/></SidePanel>}</>;
}
