'use client';
import { useEffect, useState } from 'react';
import { PointerTooltip } from '@/components/PointerTooltip';
import { companyName, priceFraming, dateLabel } from '@/lib/value/presentation';
import type { ResultEntry } from '@/app/value/_components/ResultRow';
import { CompanyLogo } from './CompanyLogo';
import { ValueLink } from './ValueLink';
import { ownerReturn, expectedReturnCopy } from '@/lib/value/owner-return';
import { listingDetails, sharePrice, marketRegion } from '@/lib/value/listing-details';
export function BuyZone({entries}:{entries:ResultEntry[]}) {
 const [page,setPage]=useState(0),[pageSize,setPageSize]=useState(8);
 useEffect(()=>{const update=()=>setPageSize(window.innerWidth<768?2:window.innerWidth<1100||window.innerHeight<=900?4:8);update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update);},[]);
 const pages=Math.max(1,Math.ceil(entries.length/pageSize)),current=Math.min(page,pages-1),visible=entries.slice(current*pageSize,current*pageSize+pageSize);
 const [hover,setHover]=useState<{entry:ResultEntry;x:number;y:number}|null>(null);
 return <section className="buy-zone" aria-labelledby="buy-zone-title"><header><div><p className="eyebrow">5 quality tests + price</p><h2 id="buy-zone-title">Buy zone <span>{entries.length}</span></h2></div><p>Quality businesses at a safety discount.</p>{pages>1&&<nav className="buy-pager" aria-label="Buy-zone pages"><button aria-label="Previous buy-zone companies" disabled={current===0} onClick={()=>setPage(current-1)}>←</button><span>{current+1}/{pages}</span><button aria-label="Next buy-zone companies" disabled={current===pages-1} onClick={()=>setPage(current+1)}>→</button></nav>}</header><div className="buy-grid">{visible.map(entry=>{const {row,mos}=entry,name=companyName(row),price=priceFraming(mos===null?null:1-mos,row.m),listing=listingDetails(row),owner=entry.historical?null:ownerReturn(row.ownerReturnInputs?.valuation??null,row.cur,row.ownerReturnInputs?.marketCapUsd??null,entry.quote);return <ValueLink key={row.id} href={`/${row.id.toLowerCase()}`} className="buy-tile" data-testid="company-tile" data-buy="true" onPointerEnter={e=>setHover({entry,x:e.clientX,y:e.clientY})} onPointerMove={e=>setHover({entry,x:e.clientX,y:e.clientY})} onPointerLeave={()=>setHover(null)} onFocus={e=>{const r=e.currentTarget.getBoundingClientRect();setHover({entry,x:r.left+r.width/2,y:r.top+20});}} onBlur={()=>setHover(null)}><CompanyLogo src={row.lg} name={name}/><strong>{name}</strong><span className="region-badge">{marketRegion(row)}</span><span className="buy-owner-return">{entry.historical?'Historical buy-zone pick':owner?expectedReturnCopy(owner):'Expected return unavailable'}</span><span className="buy-discount">{price.headline.replace('its estimated value','value')}</span><span className="buy-quote">{entry.historical?'Past-year pick':sharePrice(entry.quote,row.cur)} · {listing.country}</span><span className="buy-listing">{listing.exchange}{listing.note&&(listing.note.startsWith('A-shares')?' · A-shares*':'*')}</span></ValueLink>;})}{!entries.length&&<p className="no-buys">No buy-zone companies in this view. Try another country or year.</p>}</div>{entries.some(e=>['CN','JP'].includes(e.row.c))&&<p className="market-access">* A-shares trade in mainland China and need a broker with access. Tokyo shares need Japanese-market access; many brokers do not offer it.</p>}{hover&&<PointerTooltip x={hover.x} y={hover.y}><strong>{companyName(hover.entry.row)}</strong><div>Buy zone · passes all 5 quality tests + price</div><div>{priceFraming(hover.entry.mos===null?null:1-hover.entry.mos,hover.entry.row.m).headline}</div><div>{priceFraming(hover.entry.mos===null?null:1-hover.entry.mos,hover.entry.row.m).fall}</div>{hover.entry.seed&&<div>Price estimated from market value on {dateLabel(hover.entry.date)}</div>}<small>{hover.entry.row.id} · {hover.entry.row.s??'Sector unavailable'}</small></PointerTooltip>}</section>;
}
