'use client';
import type {Dossier,TestOutcome,PriceMap} from '@/lib/value/types';
import {T} from '@/lib/value/config';
import {tileMetric,tileReason,tileSentence} from '@/lib/value/tile-metric';
import {formatMetric,displayReturnText} from '@/lib/value/metric-labels';
import {sharePrice} from '@/lib/value/listing-details';
import {comparableValuation} from '@/lib/value/site-valuation';
import {ownerReturn} from '@/lib/value/owner-return';
import {retainedWindow,retainedSentence,yearTable} from '@/lib/value/drawer-data';
import {useWidth} from '@/lib/value/viz/use-width';
import {ThresholdSeries} from './viz/ThresholdSeries';
import {MiniPrice} from './viz/TileCharts';
import {ChartInteraction} from './viz/ChartInteraction';
import {JudgementLine} from './BusinessSection';
import {FilingEvidence} from './FilingEvidence';

function Numbers({items}:{items:Array<[string,string]>}){return <dl className="drawer-numbers">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
function WindowChart({test,currency}:{test:TestOutcome;currency:string}){
 const {ref,width,height:available}=useWidth(),w=retainedWindow(test);
 const bars=w?[{label:'Retained earnings',value:w.retained},{label:'Market value change',value:w.created}]:Object.entries(test.metrics).filter(([k])=>/financialRedFlags|restatementYears/.test(k)).map(([k,value])=>({label:k==='financialRedFlags'?'Accounting warnings':'Restatement years',value:value??0}));
 const height=Math.max(130,available-32),left=24,right=width-20,top=32,bottom=height-52,min=Math.min(0,...bars.map(b=>b.value)),max=Math.max(w?1:3,...bars.map(b=>b.value)),y=(v:number)=>bottom-(v-min)/(max-min||1)*(bottom-top);
 const fmt=(n:number)=>formatMetric({value:n,format:w?'money':'count',currency});
 return <figure ref={ref} className="window-chart"><figcaption>{w?`${w.start}–${w.end} · cumulative change across the window`:'Reported accounting checks · current assessment'}</figcaption><ChartInteraction width={width} height={height} label={w?'Retained earnings and market value':'Accounting checks'} points={bars.map((b,i)=>({x:left+(i+.5)*(right-left)/bars.length,y:y(b.value),text:`${w?`${w.start}–${w.end} · `:''}${b.label}: ${fmt(b.value)}`}))}><svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><path d={`M${left} ${y(0)}H${right}`} stroke="var(--viz-grid)"/>{bars.map((b,i)=>{const x=left+(i+.5)*(right-left)/bars.length,barWidth=Math.min(110,(right-left)/4);return <g key={b.label}><rect x={x-barWidth/2} y={Math.min(y(0),y(b.value))} width={barWidth} height={Math.max(2,Math.abs(y(b.value)-y(0)))} fill={i?'var(--buy)':'var(--viz-muted)'}/><text x={x} y={b.value>=0?y(b.value)-10:y(b.value)+18} textAnchor="middle">{fmt(b.value)}</text><text x={x} y={height-4} textAnchor="middle">{b.label}</text></g>;})}</svg></ChartInteraction></figure>;
}
function QualityChart({dossier,test}:{dossier:Dossier;test:TestOutcome}){
 const {ref,height}=useWidth(),currency=dossier.reportingCurrency??dossier.company.currency;
 const metric=tileMetric(test,dossier.company.kind,dossier.tests.understandable.series.netIncome??dossier.series.netIncome),warnings=metric.id==='financialRedFlags',series=warnings?(dossier.series.netIncome??[]):metric.series;
 return <div ref={ref as React.RefObject<HTMLDivElement>} className="panel-chart drawer-chart">{retainedWindow(test)||(warnings&&!series.length)?<WindowChart test={test} currency={currency}/>:series.length?<ThresholdSeries height={Math.max(110,height-42)} allowedBelow={test.key==='moat'?(dossier.company.kind==='operating'?T.moat.roicSecondLowest:dossier.company.kind==='bank'?.05:undefined):undefined} label={warnings?'Earnings context · warnings assessed over the window':metric.chart} series={series} domain={[series[0][0],series.at(-1)![0]]} currency={currency} format={warnings?'money':metric.chartFormat??(metric.format==='money'?'money':metric.format==='pct'||test.key==='understandable'?'pct':'ratio')} threshold={warnings||metric.chartThreshold===null?undefined:metric.chartThreshold??(test.key==='understandable'?undefined:metric.threshold)} better={metric.chartBetter??metric.better}/>:<p>{test.reasons.map(displayReturnText).join(' ')}</p>}</div>;
}
export function EvidencePanel({dossier,test}:{dossier:Dossier;test:TestOutcome}){
 const currency=dossier.reportingCurrency??dossier.valuation?.currency??dossier.company.currency;
 const metric=tileMetric(test,dossier.company.kind,dossier.tests.understandable.series.netIncome??dossier.series.netIncome),table=yearTable(dossier,test),window=retainedWindow(test);
 const values=metric.series.flatMap(([,n])=>n!=null&&Number.isFinite(n)?[n]:[]).sort((a,b)=>a-b),mid=Math.floor(values.length/2);
 const fmt=(value:number|null)=>formatMetric({value,format:metric.chartFormat==='money'?'money':metric.chartFormat==='index'?'number':metric.chartFormat==='pct'||metric.id==='opMarginCv'?'pct':metric.format,currency,returnRatio:test.key==='moat'});
 const median=values.length?values.length%2?values[mid]:(values[mid-1]+values[mid])/2:null;
 const latest=metric.series.filter(p=>p[1]!=null).at(-1)?.[1]??null;
 const stats:Array<[string,string]>=window?[['Retained',formatMetric({value:window.retained,format:'money',currency})],['Value created',formatMetric({value:window.created,format:'money',currency})],['$1 test',window.created>=window.retained?'Pass':'Fail'],['Window',`${window.start}–${window.end}`]]:values.length?[['Median',fmt(median)],['Worst',fmt(metric.id==='opMarginCv'||(metric.chartBetter??metric.better)==='higher'?values[0]:values.at(-1)!)],['Latest',fmt(latest)],['Passing bar',metric.id==='opMarginCv'?`CV ≤ ${formatMetric({value:metric.threshold,format:'x'})}`:metric.chartThreshold===null?'Over the window':`${(metric.chartBetter??metric.better)==='higher'?'≥':'<'} ${fmt(metric.chartThreshold??metric.threshold)}`],['Years',String(values.length)]]:[[metric.label,formatMetric({value:metric.value,format:metric.format,currency})],['Passing bar',formatMetric({value:metric.threshold,format:metric.format,currency})],['Years',String(table.rows.length)]];
 const answer=retainedSentence(test,currency)??(test.key==='management'||test.result==='pass'?tileSentence(test,metric,dossier.company.kind):tileReason(test));
 return <article className="evidence-layout"><p className="panel-answer">{answer||'Read the financial history and filing evidence together.'}</p><QualityChart dossier={dossier} test={test}/><Numbers items={stats}/><div className="drawer-bottom"><section className="drawer-years"><h3>Year by year <small>{currency}</small></h3><table><thead><tr><th scope="col">FY</th>{table.columns.map(c=><th scope="col" key={c.key}>{c.label}</th>)}<th scope="col" title={table.markLabel}>Bar</th></tr></thead><tbody>{table.rows.map(r=><tr key={r.year}><th scope="row">{r.year}</th>{r.values.map((v,i)=><td key={i}>{v==null?'—':formatMetric({value:v,format:table.columns[i].format,currency}).replace(`${currency} `,'')}</td>)}<td aria-label={r.pass===null?'Window assessment':r.pass?'Meets annual bar':'Below annual bar'} className={r.pass===null?'':r.pass?'year-pass':'year-fail'}>{r.pass===null?'·':r.pass?'✓':'×'}</td></tr>)}</tbody></table><p className="drawer-table-note">{table.markLabel==='Window test'?'Assessed over the full window; annual values are context.':`${table.markLabel}: ✓ meets · × below. The overall test also uses multi-year rules.`}{test.key==='moat'&&dossier.company.kind!=='insurer'?` Median ≥ ${formatMetric({value:metric.threshold,format:'pct'})}; ≥ ${formatMetric({value:dossier.company.kind==='bank'?.05:T.moat.roicSecondLowest,format:'pct'})} in all but one reported year.`:''}{window?' Profit − div. excludes buybacks and other equity movements.':''}</p></section><FilingEvidence dossier={dossier} test={test}><JudgementLine test={test}/></FilingEvidence></div></article>;
}
export function ValuationPanel({dossier,quote}:{dossier:Dossier;quote:PriceMap[string]|null}){
 const v=dossier.valuation,comparable=comparableValuation(v,dossier.company.currency),owner=ownerReturn(v,dossier.company.currency,dossier.company.marketCapUsd,quote?.[0]??null),mos=dossier.requiredMos??.25;
 if(!v)return null;
 const pct=(n:number)=>`${(n*100).toFixed(1)}%`,money=(n:number|null)=>sharePrice(n,dossier.company.currency);
 const history=dossier.valueHistory??[],prices=dossier.priceHistory??[];
 return <article className="evidence-layout"><p className="panel-answer">{dossier.b?'The price clears the safety discount and required return.':'Wait for a price that clears the safety discount and required return.'}</p><div className="panel-chart drawer-chart"><MiniPrice dossier={dossier} quote={quote} fluid minimumHeight={110}/></div><Numbers items={[["Share price",money(quote?.[0]??null)],["Estimated value",money(comparable?.perShare.mid??null)],["Buy price",money(comparable?comparable.perShare.mid*(1-mos):null)],['Expected / yr',owner?pct(owner.expected):'—'],['Required',pct(v.discountRate)]]}/><div className="drawer-bottom"><section className="drawer-years"><h3>Year by year</h3><table><thead><tr><th>FY</th><th>Price</th><th>Value</th><th>Buy below</th><th>Bar</th></tr></thead><tbody>{history.map(([fy,,mid])=>{const p=prices.filter(p=>Number(p[0].slice(0,4))===fy).at(-1)?.[1];return <tr key={fy}><th scope="row">{fy}</th><td>{money(p??null)}</td><td>{money(mid)}</td><td>{money(mid*(1-mos))}</td><td aria-label={p==null?'No year-end quote':p<=mid*(1-mos)?'Meets price bar':'Above price bar'}>{p==null?'·':p<=mid*(1-mos)?'✓':'×'}</td></tr>;})}</tbody></table><p className="drawer-table-note">Year-end price against the safety discount. Required return is a separate check.</p></section><FilingEvidence dossier={dossier}><p>{v.method==='nav'?'NAV plus reinvested dividends':v.method==='book_value'?'Book value and returns on equity':'Cash left for owners after maintaining the business'} · {pct(v.growth)} growth.</p><dl className="valuation-inputs">{v.capitalReturns&&<><div><dt>ROIC excluding acquisitions</dt><dd>{formatMetric({value:v.capitalReturns.excludingGoodwill,format:'pct',returnRatio:true})}</dd></div><div><dt>ROIC including acquisitions</dt><dd>{formatMetric({value:v.capitalReturns.includingAcquisitions,format:'pct',returnRatio:true})}</dd></div></>}{v.bridge.slice(0,5).map(r=><div key={r.label}><dt>{r.label}</dt><dd>{formatMetric({value:r.value,format:/shares/i.test(r.label)?'count':/return|CAGR/i.test(r.label)?'pct':/factor|price to book/i.test(r.label)?'x':'money',currency:v.currency})}</dd></div>)}</dl></FilingEvidence></div></article>;
}
