import type {StoreMeta,Result} from '@/lib/value/types';
import {METHOD_CHANGES} from '@/lib/value/method-version';
import {ChartInteraction} from './viz/ChartInteraction';

export type MethodData={meta:StoreMeta|null;calibration:Array<{id:string;name:string;expected:boolean;tests:Result[];why:string}>};
export function MethodDetails({meta,calibration}:MethodData){
 const populations=[['Western',meta?.western?.story],['All markets',meta?.story]] as const;
 return <>
  {meta&&<section className="method-funnel"><h3>From universe to buy zone</h3><p>{meta.counts.universe.toLocaleString('en-US')} index members · {meta.asOf.slice(0,10)}</p>{populations.map(([label,story])=>story&&<div key={label}><h4>{label}</h4>{[['Analysed',story.analysed],['Quality passes',story.qualityPasses],['Buy zone',story.atBuy]].map(([stage,count])=><div className="funnel-stage" key={stage}><span>{stage}</span><b>{Number(count).toLocaleString('en-US')}</b><ChartInteraction width={300} height={18} label={`${label}: ${stage}`} points={[{x:150,y:9,text:`${label} · ${stage}: ${count} companies · ${meta.asOf.slice(0,10)}`}]}><svg viewBox="0 0 300 18" aria-hidden="true"><rect width={300*Number(count)/meta.counts.universe} height="18" fill="var(--buy)" opacity=".5"/></svg></ChartInteraction></div>)}</div>)}</section>}
  <section className="method-calibration"><h3>Known quality and weak businesses</h3><p>Current five-test results against the development reference set; this is not an independent holdout.</p><table><thead><tr><th>Company</th><th>Expected</th><th>Five tests¹</th></tr></thead><tbody>{calibration.map(c=><tr key={c.id} title={c.why}><th><a href={`/${c.id.toLowerCase()}`}>{c.id.replace('.US','')}</a></th><td>{c.expected?'Quality':'Weak'}</td><td>{c.tests.map((t,i)=><span key={i} title={['Predictable profits','Lasting advantage','Cash for owners','Capital allocation','Honest accounts'][i]}>{t==='pass'?'✓':t==='fail'?'×':'·'} </span>)}</td></tr>)}</tbody></table><p>¹ Profits · advantage · cash · allocation · accounts. ✓ passes; × fails. Hover a company for the reference rationale.</p></section>
  <section><h3>Berkshire purchase check · 30 Sep 2026</h3><p>Historical research snapshot, before the current method. Quarterly net holding changes and restated accounts; prices are monthly-close estimates.</p><table><thead><tr><th>Sample</th><th>Cases</th><th>Buys</th><th>Within 20%</th></tr></thead><tbody>{[['All scenarios',195,1,2],['Ordinary',170,1,2],['Named cases',55,0,0],['Manager picks',5,0,0],['Regretted',7,0,0]].map(([label,...counts])=><tr key={label}><th>{label}</th>{counts.map((n,i)=><td key={i}>{n}</td>)}</tr>)}</tbody></table><p>66 of 195 cases have comparable price and value. Within 20% includes buys and requires the same quality and return hurdles. These are overlapping samples, not independent investment decisions.</p></section>
  <section><h3>Method changes</h3>{METHOD_CHANGES.map(c=><div className="method-change" key={c.version}><h4>{c.version} · {c.date}</h4><p>{c.changelog}</p></div>)}</section>
  <section><h3>Source register</h3><table><thead><tr><th>Source</th><th>Used for</th></tr></thead><tbody>{[['SEC EDGAR','US filings and 13F holdings','https://www.sec.gov/edgar/search/'],['EDINET','Japanese annual filings','https://disclosure2.edinet-fsa.go.jp/'],['ESEF','European annual filings','https://filings.xbrl.org/'],['EODHD','Normalized accounts','https://eodhd.com/'],['Yahoo Finance','Historical share prices','https://finance.yahoo.com/']].map(([name,use,url])=><tr key={name}><th><a href={url}>{name} ↗</a></th><td>{use}</td></tr>)}</tbody></table></section>
 </>;
}
