import {Fragment} from 'react';
import {displayName} from '@/lib/value/presentation';
import type {StoreMeta,Result} from '@/lib/value/types';
import {METHOD_CHANGES} from '@/lib/value/method-version';
import {ChartInteraction} from './viz/ChartInteraction';

export type MethodData={meta:StoreMeta|null;calibration:Array<{id:string;name:string;expected:boolean;tests:Result[];why:string}>};
export function MethodDetails({meta,calibration}:MethodData){
 const populations=[['Western',meta?.western?.story],['All markets',meta?.story]] as const;
 return <>
  {meta&&<section className="method-funnel"><h3>From universe to buy zone</h3><p>{meta.counts.universe.toLocaleString('en-US')} index members · {meta.asOf.slice(0,10)}</p><table><thead><tr><th>Stage</th><th>Western</th><th>All markets</th></tr></thead><tbody>{[
   {label:'Analysed',counts:populations.map(([,s])=>s?.analysed)},
   ...(meta.funnel?.gates??[]).filter(g=>g.key!=='price').map(g=>({label:g.label,counts:[meta.western?.funnel.gates.find(w=>w.key===g.key)?.passing,g.passing]})),
   {label:'Quality passes',counts:populations.map(([,s])=>s?.qualityPasses)},
   {label:'Buy zone',counts:populations.map(([,s])=>s?.atBuy)},
  ].map(row=><tr key={row.label}><th>{row.label}</th>{row.counts.map((count,i)=><td key={i}>{count?.toLocaleString('en-US')}{count!=null&&populations[i][1]?.analysed?<small> · {Math.round(count/populations[i][1]!.analysed*100)}%</small>:null}<ChartInteraction width={100} height={10} label={`${populations[i][0]}: ${row.label}`} points={[{x:50,y:5,text:`${row.label}: ${count} companies, ${meta.asOf.slice(0,10)}`}]}><svg viewBox="0 0 100 10" aria-hidden="true"><rect width={100*(count??0)/(populations[i][1]?.analysed||meta.counts.universe)} height="10" fill="var(--buy)" opacity=".5"/></svg></ChartInteraction></td>)}</tr>)}</tbody></table><p>Each test keeps only companies that passed the preceding tests. Bars and percentages show the share of analysed companies in each column.</p></section>}
  <section className="method-calibration"><h3>Known quality and weak businesses</h3><p>Current five-test results against the development reference set; this is not an independent holdout.</p><table><thead><tr><th>Company</th><th>Expected</th><th>Five tests¹</th></tr></thead><tbody>{calibration.map(c=><Fragment key={c.id}><tr><th><a href={`/${c.id.toLowerCase()}`} title={c.id}>{displayName(c.name)}</a></th><td>{c.expected?'Quality':'Weak'}</td><td>{c.tests.map((t,i)=><span key={i} title={['Predictable profits','Lasting advantage','Cash for owners','Capital allocation','Honest accounts'][i]}>{t==='pass'?'✓':t==='fail'?'×':'·'} </span>)}</td></tr><tr className="calibration-reason"><td colSpan={3}>{c.why}</td></tr></Fragment>)}</tbody></table><p>¹ Profits · advantage · cash · allocation · accounts. ✓ passes; × fails. Rationales describe the development reference expectation.</p></section>
  <section><h3>Berkshire purchase check · 30 Sep 2026</h3><p>Historical research snapshot, before the current method. Quarterly net holding changes and restated accounts; prices are monthly-close estimates.</p><table><thead><tr><th>Sample</th><th>Cases</th><th>Buys</th><th>Within 20%</th></tr></thead><tbody>{[['All scenarios',195,1,2],['Ordinary',170,1,2],['Named cases',55,0,0],['Manager picks',5,0,0],['Regretted',7,0,0]].map(([label,...counts])=><tr key={label}><th>{label}</th>{counts.map((n,i)=><td key={i}>{n}</td>)}</tr>)}</tbody></table><p>66 of 195 cases have comparable price and value. Within 20% includes buys and requires the same quality and return hurdles. These are overlapping samples, not independent investment decisions.</p></section>
  <section><h3>Method changes</h3>{METHOD_CHANGES.map(c=><div className="method-change" key={c.version}><h4>{c.version} · {c.date}</h4><p>{c.changelog}</p></div>)}</section>
  <section className="method-sources"><h3>Source register</h3><table><thead><tr><th>Source</th><th>Used for</th></tr></thead><tbody>{[['SEC EDGAR','US filings and 13F holdings','https://www.sec.gov/edgar/search/'],['EDINET','Japanese annual filings','https://disclosure2.edinet-fsa.go.jp/'],['ESEF','European annual filings','https://filings.xbrl.org/'],['EODHD','Normalized accounts','https://eodhd.com/'],['Yahoo Finance','Historical share prices','https://finance.yahoo.com/']].map(([name,use,url])=><tr key={name}><th><a href={url}>{name} ↗</a></th><td>{use}</td></tr>)}</tbody></table></section>
 </>;
}
