'use client';
import { useEffect, useState } from 'react';
import { ResultRow, type ResultEntry } from './ResultRow';
export type Sort = 'name' | 'country' | 'cap' | 'mos' | 'holders' | 'return';
export const columns: Array<[Sort,string]> = [['name','Company'],['country','Country'],['cap','Market cap (USD)'],['mos','Price / value'],['holders','Holders'],['return','Return']];
export function ResultsTable({ entries, sort, direction, sortBy, expanded = false }: { expanded?:boolean; entries: ResultEntry[]; sort: Sort; direction: number; sortBy: (key: Sort)=>void }) {
 const [scroll,setScroll]=useState(0), [rowHeight,setRowHeight]=useState(56), virtual=entries.length>60;
 useEffect(()=>{const media=window.matchMedia('(max-width:767px)');const update=()=>setRowHeight(media.matches?96:56);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const start=virtual ? Math.min(Math.max(0,entries.length-50),Math.max(0,Math.floor(scroll/rowHeight)-10)):0;
 const ratios=entries.flatMap(e=>e.mos===null?[]:[1-e.mos]);
 const maximum=Math.max(4,...ratios.map(n=>2**Math.ceil(Math.log2(n)))), minimum=Math.min(.25,...ratios.map(n=>2**Math.floor(Math.log2(n))));
 const visible=virtual?entries.slice(start,start+50):entries;
 const head=(key:Sort,label:string,cls='')=><th className={cls} aria-sort={sort===key?(key==='mos'?-direction:direction)===1?'ascending':'descending':'none'}><button onClick={()=>sortBy(key)}><span title={key==='return'?'● year below 15%':undefined}>{label}</span> <span aria-hidden="true">{sort===key?(key==='mos'?-direction:direction)===1?'↑':'↓':'↕'}</span></button>{key==='mos'&&<span className="table-ratio-scale" aria-label={`Log ratio scale ${minimum} to ${maximum}`} >{[minimum,1,maximum].filter((v,i,a)=>a.indexOf(v)===i).map(v=><small key={v} style={{left:`${(Math.log2(v)-Math.log2(minimum))/(Math.log2(maximum)-Math.log2(minimum))*100}%`}}>{v}×</small>)}</span>}</th>;
 return <div data-testid="results-scroll" style={virtual?{maxHeight:650,overflowY:'auto'}:undefined} onScroll={e=>setScroll(e.currentTarget.scrollTop)}><table aria-rowcount={entries.length+1} data-testid="results-table" className={`results-table ${virtual?'value-virtual':''}`}><thead><tr>{head('name','Company')}{head('country','Country','country-col')}<th className="sector-col">Sector</th>{head('cap','Market cap (USD)','cap-col')}{head('return','Return · 10 years','roic-col')}{head('mos','Price / value','price-col')}{head('holders','Holders','holders-col')}<th className="quality-col">{expanded?<div>{['Understandable','Moat','Economics','Management','Accounting','Price'].map((label,i)=><abbr key={label} title={label}>{['U','M','E','Mg','A','P'][i]}</abbr>)}</div>:'Tests'}</th></tr></thead><tbody>{start>0&&<tr aria-hidden="true"><td colSpan={9} style={{height:start*rowHeight}}/></tr>}{visible.map((entry,i)=><ResultRow expanded={expanded} key={entry.row.id} rowIndex={start+i+2} maximum={maximum} minimum={minimum} {...entry}/>)}{virtual&&start+visible.length<entries.length&&<tr aria-hidden="true"><td colSpan={9} style={{height:(entries.length-start-visible.length)*rowHeight}}/></tr>}</tbody></table></div>;
}
