import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import path from 'node:path';
const store=process.env.VALUE_STORE_DIR;
test.skip(!process.env.VALUE_QUARTERLY_QA||!store,'Requires local quarterly staging');
const read=(file:string)=>JSON.parse(readFileSync(path.join(store!,file),'utf8'));
for(const [width,height] of [[1728,970],[2056,1180],[1440,800],[390,844]])test(`quarter navigation and layout ${width}`,async({page})=>{
 await page.setViewportSize({width,height});
 await page.goto('/?q=2018Q3',{waitUntil:'networkidle'});
 const slider=page.getByRole('slider',{name:'Quarter'}),view=page.locator('.main-view');
 await expect(view).toHaveAttribute('data-frame','2018Q3');
 await expect(slider).toHaveAttribute('aria-valuetext','2018Q3');
 const index=read('history/index.json');
 await expect(page.locator('.one-index')).toHaveAttribute('data-buy-count',String(index.western.perQuarter['2018Q3'].atBuy));
 await expect(page.locator('.main-zone-heading').first()).toContainText('Expected return / yr');
 await page.waitForTimeout(1400);
 await page.locator('h1').click();await page.keyboard.press('ArrowLeft');
 await expect(view).toHaveAttribute('data-frame','2018Q2');
 await expect(page).toHaveURL(/q=2018Q2/);
 await page.keyboard.press('ArrowRight');await expect(view).toHaveAttribute('data-frame','2018Q3');
 await slider.press('End');await expect(view).toHaveAttribute('data-frame','Today');
 await expect(page).not.toHaveURL(/[?&](q|year)=/);
 await slider.press('Home');await expect(view).toHaveAttribute('data-frame','2005Q1');
 const rect=(await slider.boundingBox())!;
 await page.mouse.click(rect.x+rect.width*.6,rect.y+rect.height/2);
 await expect(view).not.toHaveAttribute('data-frame','2005Q1');
 await page.mouse.move(rect.x+rect.width*.6,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.7,rect.y+rect.height/2,{steps:8});await page.mouse.up();
 await expect(view).toHaveAttribute('aria-busy','false');
 const frame=await view.getAttribute('data-frame');await expect(slider).toHaveAttribute('aria-valuetext',frame!);
 await page.waitForTimeout(400);await page.reload({waitUntil:'networkidle'});await expect(view).toHaveAttribute('data-frame',frame!);
 const layout=await page.evaluate(()=>({w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,fonts:[...document.querySelectorAll('.house-track span')].filter(e=>e.getBoundingClientRect().width).map(e=>parseFloat(getComputedStyle(e).fontSize))}));
 expect(layout.w).toBeLessThanOrEqual(width);if(width>=768)expect(layout.h).toBeLessThanOrEqual(height);
 expect(layout.fonts.every(n=>n>=13)).toBe(true);
});
test('legacy year links select Q4 and survive browser back',async({page})=>{
 await page.goto('/?year=2018',{waitUntil:'networkidle'});
 await expect(page.locator('.main-view')).toHaveAttribute('data-frame','2018Q4');
 await page.keyboard.press('ArrowRight');await expect(page).toHaveURL(/q=2019Q1/);
 await expect(page).not.toHaveURL(/year=/);await page.goBack();
 await expect(page.locator('.main-view')).toHaveAttribute('data-frame','2018Q4');
});
