import type {Counterparty} from './types';
/** Reviewed entity aliases; this is an identity dictionary, never a source of edges. */
export const IDENTITIES:Counterparty[]=[
 {id:'MSFT.US',name:'Microsoft',aliases:['Microsoft Corporation','Microsoft Corp.'],wikidata:'Q2283'},
 {id:'ORCL.US',name:'Oracle',aliases:['Oracle Corporation'],wikidata:'Q19900'},
 {id:'META.US',name:'Meta',aliases:['Meta Platforms','Facebook','Meta Platforms Inc.'],wikidata:'Q380'},
 {id:'GOOGL.US',name:'Alphabet',aliases:['Google','Google LLC','Alphabet Inc.'],wikidata:'Q20800404'},
 {id:'AMZN.US',name:'Amazon',aliases:['Amazon.com','Amazon Web Services','AWS'],wikidata:'Q3884'},
 {id:'NVDA.US',name:'Nvidia',aliases:['NVIDIA Corporation'],wikidata:'Q182477'},
 {id:'AMD.US',name:'AMD',aliases:['Advanced Micro Devices'],wikidata:'Q128896'},
 {id:'AVGO.US',name:'Broadcom',aliases:['Broadcom Inc.'],wikidata:'Q555351'},
 {id:'CRWV.US',name:'CoreWeave',aliases:['CoreWeave Inc.'],wikidata:'Q118502379'},
 {id:'AAPL.US',name:'Apple',aliases:['Apple Inc.'],wikidata:'Q312'},
 {id:'2330.TW',name:'TSMC',aliases:['Taiwan Semiconductor','Taiwan Semiconductor Manufacturing Company','Taiwan Semiconductor Manufacturing Company Limited'],wikidata:'Q713418'},
 {id:'QCOM.US',name:'Qualcomm',aliases:['QUALCOMM Incorporated'],wikidata:'Q544847'},
 {id:'SWKS.US',name:'Skyworks',aliases:['Skyworks Solutions'],wikidata:'Q7537389'},
 {id:'MU.US',name:'Micron',aliases:['Micron Technology'],wikidata:'Q218542'},
 {id:'INTC.US',name:'Intel',aliases:['Intel Corporation'],wikidata:'Q248'},
 {id:'005930.KO',name:'Samsung Electronics',aliases:['Samsung','Samsung Electronics Co., Ltd.'],wikidata:'Q20718'},
 {id:'000660.KO',name:'SK hynix',aliases:['SK Hynix Inc.'],wikidata:'Q33748'},
 {id:'6758.JP',name:'Sony',aliases:['Sony Group','Sony Interactive Entertainment'],wikidata:'Q41187'},
 {id:'ARM.US',name:'Arm',aliases:['Arm Holdings'],wikidata:'Q47934'},
 {id:'RIVN.US',name:'Rivian',aliases:['Rivian Automotive'],wikidata:'Q21535349'},
 {id:'1810.HK',name:'Xiaomi',aliases:['Xiaomi Corporation'],wikidata:'Q1636958'},
 {id:'2317.TW',name:'Hon Hai',aliases:['Foxconn','Hon Hai Precision'],wikidata:'Q463094'},
 {id:'OWL.US',name:'Blue Owl',aliases:['Blue Owl Capital'],wikidata:'Q106847444'},
 {id:'CORZ.US',name:'Core Scientific',aliases:['Core Scientific Inc.']},
 {id:'external:openai',name:'OpenAI',aliases:['OpenAI OpCo','OpenAI Global','OpenAI Group'],wikidata:'Q21708200'},
 {id:'external:anthropic',name:'Anthropic',aliases:['Anthropic PBC'],wikidata:'Q110634815'},
];
