import json,pathlib
p=pathlib.Path.home()/'data/value-logos';e=p/'evidence';rows=json.loads((e/'random-40.json').read_text());web={r['id']:r for r in json.loads((e/'websites/results.json').read_text())};alt={r['id']:r for r in json.loads((e/'alternate-websites/results.json').read_text())}
notes={'LBRT':'Red oval L / LIBERTY mark matches Liberty Energy, not Liberty media','WING':'Green winged Wingstop mark; shopping-bag candidate rejected','LYFT':'Pink lowercase lyft wordmark','PSEC':'Blue Prospect Capital wordmark','EQX':'Gold interlocking rings / EQUINOX GOLD','CNX':'Blue/gray CNX wordmark; flame artwork rejected','WT':'WisdomTree tree and wordmark','UVSP':'Univest blue/gold U shield','ATRO':'Astronics wordmark; cabin photograph rejected','CNA':'Red CNA wordmark from official site header asset','CTRI':'Multicolored geometric Centuri symbol and wordmark','LNC':'Updated burgundy Lincoln portrait and Financial wordmark','VSNT':'Versant white wordmark, dark canvas preserves contrast','LIND':'National Geographic / Lindblad Expeditions co-brand matches company site','SBSI':'Southside Bank S mark and wordmark','RBRK':'Teal geometric ring / gray rubrik wordmark matches official One Passport header','PDS':'Green interlocking Precision Drilling mark','HRB':'Official H&R BLOCK green square from MyBlock header; replaces smaller horizontal version','AGI':'Gold/black triangular Alamos Gold corporate mark matches official project-site header','EMBC':'Purple embecta wordmark and multicolor symbol','OSK':'Black hexagonal Oshkosh symbol and wordmark','PYIYF':'Gray PFI initials with red corner','OSUR':'OraSure Technologies wordmark and symbol','LTH':'Black LIFE TIME wordmark','PBF':'PBF Energy red oval / blue initials','LAB':'Standard BioTools oval / star symbol','ENOV':'Black enovis wordmark','BOOM':'DMC black spiral and initials','HGV':'Hilton Grand Vacations blue/teal wordmark','ESI':'Element Solutions blue geometric symbol','KC':'Kingsoft Cloud red cloud mark','MKTX':'MarketAxess blue/gray crossed-line mark','TPHS':'Trinity Place Holdings blue wordmark','HUBS':'HubSpot gray/orange wordmark; event badge rejected','AS':'Amer Sports blue wordmark','FIVN':'Five9 blue wordmark','UTI':'Universal Technical Institute red/blue U','SSL':'Sasol blue molecular mark and wordmark','DOX':'Updated gradient a/amdocs mark matched to official 2025 brochure; old green mark replaced','RIG':'Transocean blue wordmark and red symbol'}
special={
'CNA.US':('https://www.cna.com/','CNA-official-image'),
'RBRK.US':('https://onepassport.rubrik.com/','RBRK-official-page.png'),
'HRB.US':('https://account.hrblock.com/','HRB-official-page.png'),
'AGI.US':('https://lynnlake.alamosgold.com/vendors/contracting-considerations/','AGI-official.png'),
'DOX.US':('https://solutions.amdocs.com/rs/647-OJR-802/images/Amdocs-data-and-ai-brochure-for-financial-services-02-2025.pdf','DOX-official.png')}
audit=[]
for row in rows:
 id=row['id'];r=json.loads((p/'bundle/records'/f'{id}.json').read_text());w=web[id];url=w.get('url',row['website']);reference='websites/'+id+'.png'
 if id in ['LYFT.US','WT.US','CNX.US','ESI.US']:url=alt[id]['url'];reference='alternate-websites/'+id+'.png'
 if id in ['LTH.US','PYIYF.US','KC.US']:reference='websites/'+id+'-loaded.png'
 if id in special:url,reference=special[id]
 assert (e/reference).exists(),reference
 audit.append({'id':id,'name':row['n'],'sampleWebsite':row['website'],'referenceUrl':url.split('?')[0],'referenceFile':reference,'sourceUrl':r.get('sourceUrl'),'asset':r.get('asset'),'decision':'pass','note':notes[id.split('.')[0]],'checkedSizesPx':[26,64],'checkedBackgrounds':['light','dark']})
(e/'random-40-audit.json').write_text(json.dumps({'seed':20261005,'selection':'random.Random(20261005).sample(sorted(missing_before,key=id),40), selected before inspection; no redraw','reviewer':'Codex, manual visual comparison','count':40,'passed':40,'records':audit},indent=2)+'\n')
print('Website audit: 40/40; reference files present')
