import json,csv
from pathlib import Path
r=Path('/Users/miki/data/value-rules/.audit/rules-6');e=r/'evidence';d=json.loads((r/'research/decision-metrics.json').read_text())
variants=['sbc_once','current_scale','ttm_maintenance','parent_allocation','ocf_fallback','flow_inputs','combined']
labels={'sbc_once':'SBC charged once','current_scale':'Current revenue × median margin','ttm_maintenance':'TTM maintenance estimator','parent_allocation':'Same-period parent allocation','ocf_fallback':'Missing-NI OCF fallback / maintenance','flow_inputs':'Flow corrections together','combined':'Combined shipping accounting'}
cols=[('US','train'),('US','later'),('Western_nonUS','train'),('Western_nonUS','later'),('all_nonUS','train'),('all_nonUS','later')]
lookup={(x['variant'],x['scope'],x['period']):x for x in d['gates']}
lines=['Method 3.6.0 — owner correctness override, 7 October 2026','', 'Replay coverage: 2,058 identities and 99,691 company-quarter rows; 93,961 paired, 5,572 reporting/trading-currency mismatches excluded and 158 snapshots unavailable.','', 'Annual-return changes below are percentage points against the same baseline. Training is 2005–2015; later is 2016–2026. U.S. later is CONTAMINATED by prior inspection and is not an untouched holdout. The legacy return gate rejects SBC/current-scale/combined; accounting correctness still ships under the explicit owner instruction.','', '| Correction | U.S. train | U.S. later (contaminated) | Western ex-U.S. train | Western ex-U.S. later | All ex-U.S. train | All ex-U.S. later |','|---|---:|---:|---:|---:|---:|---:|']
for v in variants:lines.append('| '+labels[v]+' | '+' | '.join(f"{lookup[v,*c]['cagr_change_pp']:+.3f}"for c in cols)+' |')
lines+=['','The complete decision-metrics.json and backtest-fixes.csv retain drawdown changes, missing-return allocations, new-buy cohorts and legacy gate results. Positive drawdown delta means a less severe worst drawdown. This is a retrospective diagnostic with survivorship, restatement, present bond inputs and incomplete return/FX coverage; no causal or point-in-time performance claim.','', 'Raw-provider TTM flow clearing has no separate historical replay effect: quarterly-snapshot replay already constructs its own TTM flows and does not call raw trailingInputs. Its regression fixtures demonstrate the cleared annual judgement/lease/consolidated-profit leakage. FX-refresh, canonical-identity and cached-share publication fixes are publication-layer corrections outside this historical engine; historical return impact is not measured, and is not presented as zero. Their complete current-release impact is in the release audit and proposal manifest.','', 'Ambiguous maintenance working-capital reinvestment, issuer-specific lease/ROU overlap and cash-attributable after-tax interest remain disclosed limitations. No invented adjustment is included in the replay or release.']
(e/'backtest-summary.md').write_text('\n'.join(lines)+'\n')
with (e/'backtest-fixes.csv').open('w')as f:
 w=csv.DictWriter(f,fieldnames=list(d['gates'][0]));w.writeheader();w.writerows(d['gates'])
