import type { JevQuestion } from '../types';
import type { ThesisQuestionId } from './types';
export const THESIS_VERSION='2';
const context='Use only actual company disclosures in the supplied filing passages, never outside knowledge or hypothetical risk factors. Dates are relative to the AS OF date in the state. A risk that might happen is not an event that has happened. ';
export const THESIS_QUESTIONS:Record<ThesisQuestionId,JevQuestion>={
 thesis_structural:{type:'choice',instructions:context+'Has the company disclosed a structural decline in its core business in the last 18 months (loss of key product exclusivity/patent, permanent loss of market share, a major customer or license, regulatory ban), not a cyclical dip? Temporary production interruptions, cyclical demand and prospective competition alone are not structural decline.',criteria:{yes:'Actual structural decline disclosed within 18 months',no:'No such structural decline disclosed',unclear:'A disclosed change cannot be distinguished from a cyclical or temporary dip'}},
 thesis_liability:{type:'choice',instructions:context+'Does the company disclose a provision, contingent liability or regulatory redress programme that could exceed 10% of shareholders’ equity? Compare stated amounts with same-currency equity supplied in the state or filing. Require a disclosed monetary exposure or explicit statement that supports this threshold; an unquantified routine litigation risk alone is NO. Negative equity with positive disclosed charges exceeds the threshold.',criteria:{yes:'Disclosed exposure could exceed 10% of equity',no:'No disclosed exposure supporting that threshold'}},
 thesis_guidance:{type:'choice',instructions:context+'Has management guided to a fall in revenue or operating profit of MORE THAN 20% for the current full financial year? Require forward guidance, not a completed-year result, quarterly guidance, EPS guidance or a hypothetical scenario. Exactly 20% does not qualify.',criteria:{yes:'Current full-year revenue or operating-profit guidance implies a fall greater than 20%',no:'No qualifying current full-year guidance'}},
 thesis_distress:{type:'choice',instructions:context+'Is there a going-concern, covenant breach or dividend suspension disclosure? Going concern means material uncertainty or substantial doubt, NOT the standard going-concern basis or a positive viability assessment. Require an actual covenant breach or a suspended/cancelled ordinary dividend, not a general risk of breach or a routine statement that dividends are discretionary. An ongoing suspension qualifies; a explicitly resolved historical event does not.',criteria:{yes:'Actual going-concern doubt, covenant breach or ongoing dividend suspension disclosed',no:'No such disclosure'}},
};
