import hashlib,json,re,shutil
from pathlib import Path
r=Path('/Users/miki/data/value-rules/.audit/rules-2');e=r/'evidence';d=Path('docs/value/rules-2');bundle=Path('/Users/miki/data/value-rules/release-bundle')
read=lambda p:json.loads(p.read_text())
a=read(e/'release-audit.json');v=read(e/'verification.json');browser=read(e/'browser-comparison.json');method=read(e/'method-attribution.json');changes=read(e/'quality-changes.json');buys=read(e/'buy-evidence.json');cache=read(e/'retained-cache-failures.json');attribution=read(e/'attribution-summary.json')
rawById={row['id']:row for row in method}
assert v['passed'];approval=Path('scripts/value/approved-verdict-changes.json');digest=hashlib.sha256(approval.read_bytes()).hexdigest()
unit=(e/'unit-final-isolated.log').read_text();unitSummary='; '.join(line.strip().replace('|', '/')for line in unit.splitlines()if re.search(r'^\s*(Test Files|Tests)\s',line))
text=['READY','','# rules-2 — 3.5.0 judges the record, not one bad year','',
'All required local technical gates passed. **Buy approval is pending. Nothing was pushed or published externally.** The exact proposed manifest below is for the owner to approve; the real publish harness used only a local bare remote and stub Blob. READY does not authorize the controller commands.', '',
'`value-rules` is rebased onto `origin/master` `c75d682`. The bound live archive is `2d7f1d84db5b28e474a04b8b7f94b29621acbb5f`, with 3,915 dossiers. The reviewed 3.5.0 rule sources are byte-identical to rules-1 `e5e346c`; no return experiment was reopened or threshold tuned. The final local commit, with message `value: 3.5.0 judges the record, not one bad year`, is bound as `codeCommit` in `release-bundle/manifest.json`.', '',
'| Gate | Result |','|---|---|',f'| Full unit suite | PASS — {unitSummary} |','| Production build | PASS, including TypeScript; exact Inter dependency hash in font-dependency.json |','| Ordinary export | PASS; 3,915 dossiers, no missing or added company |','| Real publish harness | PASS; production calibration, invariants, commit, local transport and stub Blob |',f"| Blob integrity | PASS — {v['blobFiles']} files, {v['blobBytes']:,} bytes, equal to the local committed snapshot |",'| Local post-publish | PASS; current/quarter-back/2018Q3 checks, no page errors, pending receipt cleared |',f"| Browser | PASS — {browser['candidateStates']} layout states; 20 quality + 10 price surface audits across {browser['semanticStates']} company/viewport pairs; NVDA, EME, 001800, 000786, IPS; desktop 1728×970 and mobile 390×844; zero new findings |",f"| Source/archive binding | PASS — {v['sourceBindings']:,} source files and {v['liveArchiveFiles']:,} archive files; zero mismatches |",'',
'## Scope and attribution','',
'The fresh corpus copy used independent files. Every mutating validation command ran in an isolated namespace with loopback only, no external routes, and the live corpus mounted read-only. Tests explicitly used temporary `VALUE_CORPUS_DIR` directories. No daily-runner lock or live hold was opened or modified. No EODHD acquisition, fresh Jev reading, subagent, external push or publication occurred.', '',
'The 3.4.0 control ran the production analysis stage for every released identity. The 3.5.0 nightly analysis covered the entire normal universe with cached fundamentals, in four disjoint batches through the same stage; `full-nightly-scope.json` records the union and every ID. Cached Jev answers were accepted only when their exact section hash and question version matched. Analysis and publication comparisons are separate: `method-attribution.json` contains raw method effects, while the table below records the exposed live-to-candidate changes.', '',
'```text',*(line for line in(e/'analyze-control.log').read_text().splitlines()if re.match(r'analyze: \d+ written',line)),*(line for line in(e/'analyze-candidate.log').read_text().splitlines()if re.match(r'analyze: \d+ written|Full nightly scope:',line)),'```','',
f"There are {len(method)} raw method quality-mask changes and {len(changes)} exposed live-to-candidate mask changes. Exposed all-five passes gained: {len(a['qualityGained'])}; lost: {len(a['qualityLost'])}. Buy changes: {len(buys)}. All raw method changes use identical memo inputs, and the 3.4 control reproduces live quality masks with zero drift. No unrelated test changes are attributed to 3.5.0; see `attribution-summary.json` and `release-audit.json`.",'',
f"NVDA changes from FFPPP to PPPPP. Its raw operating-margin CV remains 0.4000636245; the fully recovered FY2023 dip yields adjusted CV 0.3311438375 against the unchanged 0.35 limit. Typical gross margin is 62.16710146%, recent margin 71.06808436%, so no decline exceeds the unchanged 4pp limit. Its 50% required margin remains unchanged. At the cached USD 238.90 quote (2026-10-05), its preserved midpoint is USD 25.298143 and Buy ceiling USD 12.649071, so it remains non-Buy. The exact production gate is in `price-gate-proof.json`.",'',
'## Proposed exact Buy approvals — pending','',f'Approval-manifest SHA-256: `{digest}`. The manifest contains exactly the Buy changes shown here, including both quality masks, valuation tuples and required margins. The invariant still rejects partial/mismatched approvals; legacy balance approvals still require unchanged quality. Each surviving-company Buy flip is also checked individually, so opposite unapproved flips cannot cancel in country/default totals. Red/green regression logs are retained.','',
'| Company | Quality | Buy | Quote | Midpoint | Required margin | Buy ceiling | Expected / required return |','|---|---|---|---:|---:|---:|---:|---|']
for row in buys:
 b,z=row['before'],row['after'];expected=row.get('expectedReturn');required=row.get('requiredReturn')
 text.append(f"| {row['id']} ({row['name']}) | {b['t']} → {z['t']} | {b['b']} → {z['b']} | {row['currency']} {row['quote'][0]:,.6f} ({row['quote'][1]}) | {z['v'][1]:,.6f} | {z['m']:.0%} | {row['buyCeiling']:,.6f} | {'Cash covers price' if row['cashCoversPrice'] else str(expected) if expected is None else f'{expected:.6%}'} / {str(required) if required is None else f'{required:.2%}'} |")
text+=['']
for row in buys:
 m=row['methodEvidence']['metrics'];text.append(f"**{row['id']}** — "+next(v['reason']for v in read(approval)if v['id']==row['id']))
 text.append(f"Valuation tuple unchanged from live: {row['valuationUnchanged']}; required margin unchanged: {row['marginUnchanged']}. `buy-evidence.json` includes the complete annual numerator/denominator series, cached file hashes, production price gate and cash-flow expected-return result.")
 text.append('')
text+=['The provider URLs in the manifest identify the cached numerical source; no live provider request was made. The wrong Orion US filing is explicitly rejected as evidence for Korea; the existing western-listing field ORN.US is also an inherited identity concern, not corroboration. For 001800.KO, the unchanged return model has immediate cash of KRW 23,898.499640 per share, exceeding the KRW 22,900 quote; the production cash-covered-price branch passes without inventing a finite IRR. The available Ipsos filing does not by itself corroborate the abrupt vendor gross-profit classification. These are source limitations for the owner’s decision, not new verified issuer facts.','',
'FDJU.PA and INMD.US were already non-Buy in the bound live archive, so their old rules-1 proposals are not carried into this manifest. NTB.US and CFG-PH.US have unrelated raw Buy proposals and remain complete-record holds.','',
'## Preservation and the prior blockers','',
f"- **R1:** complete-statement balance selection and published-denominator preservation remain unchanged. No newly hidden valuation ({len(a['valuationLosses'])}); EXR’s already released disposition remains part of the baseline.",f"- **R2:** only the {len(buys)} exact 3.5.0 Buy proposals enter the local harness manifest. Unrelated Buy proposals remain complete-record freezes. All {a['freezeCount']} explicit frozen dossiers match live as parsed records; the freeze file itself is unchanged.",'- **R3:** raw and exposed quality changes are both enumerated, with same-input control bindings, changed tests, reasons and numerical evidence. No unrelated test or threshold was relaxed.',f"- **R4:** {a['numericNulls']} numeric-to-null cells, {a['numericRemoved']} missing numeric cells and {len(a['protectedChanges'])} protected price/history/forward changes. Fiscal records are matched by fiscal key, not array position. Historical method-version labels advance; the 2,093 identity rows may reorder but all per-ID fields remain unchanged. Dated observations remain unchanged.",'- **R5:** the same regress-2 comparison rule is used. Final browser arms run sequentially with fresh runtime ISR pages for the five companies and the same verified build. Accepted chrome/whitespace and exact pre-existing findings remain explicitly listed. Hidden `.valuation-math` on unified pages is recorded as an existing live finding; price-drawer arithmetic is separately checked. NVDA also has a pre-existing disagreement between test-series and dossier-series shares (including FY2020: 24.72bn versus 25.2bn); the complete set of conflicts matches live exactly. Those figures are preserved under R1/R4 and the unchanged conflict is classified under R5. Both quality surface audits and the price audit complete for every viewport, retaining their strict failures. Raw checker failures are not relabelled as clean raw passes.',f"- **R6:** {len(cache)} failed cache bindings retain the original analysis/input/fingerprint bytes, or remain absent when absent at baseline. Their IDs and hashes are in `retained-cache-failures.json`; none is included in the overlay.", '',
'RACE.MI and STLAM.MI already exist in the released universe. The ordinary alias invariant passes without a special waiver. Already published additions were advanced into the existing coverage baseline using their pre-analysis hashes, as in regress-2; refreshed analyses remain refreshable and first-publication filing checks stay strict. No six-company proof-only freeze from rules-1 was introduced.', '',
'A preservation/presentation regression found during this proof is fixed generally: the public test carries its gross-margin basis even when the new supporting metrics are omitted. A retained 3.4 gross-margin diagnostic remains visible as FY2019–20 minus FY2023 (prior assessment), without a current pass/fail bar. Frozen legacy tests retain their original fiscal rule. No historical numeric observation is erased, and the frozen 3.5 numerical rule sources are unchanged. Regression tests cover public projection, retention, rule reconstruction and rendered labeling. The first browser comparison also caught clipped recovered-dip explanations on NVDA and EME: the shared predictable-profits drawer is now 360px instead of 300px in the 970–1049px desktop-height band, preserving the same width for every company and all evidence text. The final comparison reruns both candidate and live.','',
'## Every exposed quality change','',
'Masks are Understandable / Moat / Economics / Management / Accounting; P=pass, F=fail, U=unclear. All-five quality does not imply Buy. Each row has before/after metrics in `quality-changes.json`; full numerical series and the same-input proof are in `method-attribution.json`.', '',
'| Company | Live → 3.5.0 | All five | Buy | Changed test evidence |','|---|---|---|---|---|']
for row in changes:
 def reason(k):
  raw=rawById[row['id']]['evidence'][k]['after'];m=raw['metrics']
  if k=='moat':
   if m.get('grossMarginDrop') is None:return 'Supporting gross-margin check unavailable with incomplete/gapped history; capital-return gates pass. This is not demonstrated margin recovery.'
   return f"typical {m['grossMarginTypical']:.4%}; recent {m['grossMarginRecent']:.4%}; decline {100*m['grossMarginDrop']:.4f}pp / 4pp limit"
  return '; '.join(raw['reasons'])+f" Raw CV {m.get('opMarginCv')}; adjusted CV {m.get('opMarginRecoveredCv')} / 0.35 limit"
 reasons='; '.join(k+': '+reason(k)for k in row['changedTests']).replace('|','/')
 text.append(f"| {row['id']} | {row['before']} → {row['after']} | {row['qualityBefore']} → {row['qualityAfter']} | {row['buyBefore']} → {row['buyAfter']} | {reasons} |")
text+=['','## Raw method changes withheld by publication preservation','','| Company | Raw control → candidate | Disposition |','|---|---|---|']
exposed={v['id']for v in changes}
for row in method:
 if row['id']not in exposed:text.append(f"| {row['id']} | {row['before']} → {row['after']} | Retained released record under existing publication preservation; see raw attribution and freeze evidence |")
text+=['','## Artifacts and cleanup','',
'`/Users/miki/data/value-rules/release-bundle/` retains the scoped installable overlay, exact source/archive bindings, proposed Buy manifest, compressed candidate and evidence. `docs/value/rules-2/` retains the report, gate receipts and review evidence. Disposable corpus, control, baseline, candidate, bare remote, Blob and build copies are removed at handoff; the pre-existing dependency symlink is not a copied dependency tree and its target is untouched.', '',
f"Minimum recorded free space: `/` {v['minimumFreeBytes']['/']/1024**3:.3f} GiB; `~/data` {v['minimumFreeBytes']['/Users/miki/data']/1024**3:.3f} GiB. The 4 GiB floor was never crossed.", '',
(d/'controller-commands.md').read_text()]
report='\n'.join(text).rstrip()+'\n';(d/'report.md').write_text(report)
external=Path('/Users/miki/GitHub/superinvestors-wt/value/.superpowers/sdd/2026-09-29-value/rules-2-report.md');external.write_text(report)
for name in ['verification','release-audit','quality-changes','method-attribution','attribution-summary','buy-evidence','proposed-buy-approvals','retained-cache-failures','browser-comparison','price-gate-proof','input-integrity','frozen-rule-binding','unrelated-buy-proposals-held','release-baseline-transition','isolation','secret-scan','live-check','numeric-nulls','numeric-removed','diagnostic-basis-proof','live-archive-final','font-dependency']:
 shutil.copy2(e/(name+'.json'),d/(name+'.json'))
for name in ['unit-final-isolated','build-candidate','publish-out-final','publish-real','post-check']:
 for ext in ['log','exit']:shutil.copy2(e/(name+'.'+ext),d/(name+'.'+ext))
for name in ['approval-red.log','approval-green.log','offset-red.log','offset-green.log','diagnostic-red.log','diagnostic-green.log']:shutil.copy2(e/name,d/name)
# Keep byte-exact logs in the evidence archive; normalize display copies only.
for p in d.glob('*.log'):
 plain=re.sub(r'\x1b\[[0-9;]*m','',p.read_text())
 p.write_text('\n'.join(line.rstrip()for line in plain.splitlines()).rstrip()+'\n')
print('Report written:',external)
