import os,json
from pathlib import Path
root=Path(os.environ['PUBFIX_ROOT']);e=root/'evidence'
read=lambda p:json.loads(p.read_text())
summary=read(e/'comparison.json');rows=read(e/'changed-valuations.json');byid={r['id']:r for r in rows}
audit=read(e/'final-audit.json');cleanup=read(e/'cleanup.json');browser=read(e/'browser.json')
approved={r['id'] for r in read(Path('scripts/value/approved-verdict-changes.json'))}
flips=summary['changedBuyVerdicts'];pending=[r['id'] for r in flips if r['id'] not in approved]
status='READY' if not pending and audit['realExit']==0 and not summary['unrelated'] else 'NOT'
num=lambda x:'unavailable' if x is None else f'{x:,.6f}'
lines=[status,'',f'Branch `value-jev-2`, based on freshly fetched `origin/master` `ab804f26a4ef567e65803a4251c7031da009ef5b`. Commit title: `value: valuations use the latest filed balance sheet`. The original reader experiment remains on `value-jev` at `352c4a8`; none of its reader, judgement integration or owner-memo integration is included in this shipping branch. No additional Jev calls were made.','',
'**Decision**','',
('The publication guard rejects additional unapproved balance-driven verdict changes. Only ALSN and FDJU were controller-approved. The other transitions below are NOT treated as approved, and no freeze or threshold was added to conceal them. The requested successful real-path gate therefore remains unmet.' if pending else 'The ordinary real publish path and the controller-approved transition guard passed.'),'',
'**Complete Buy-now verdict changes**','',
'Values are per share in reporting currency; Plus500 is USD, not its GBX quote currency. Prices, FX, quality decisions and reviewed share denominators are unchanged.','',
'| Dossier | Before → after | Value before → after | Required margin | Approval | Balance source |','|---|---|---:|---:|---|---|']
for flip in flips:
 r=byid[flip['id']];verdict=lambda b:'buy' if b else 'wait'
 lines.append(f"| {r['id']} | {verdict(r['beforeBuy'])} → {verdict(r['afterBuy'])} | {r['currency']} {num(r['beforeValue'])} → {num(r['afterValue'])} | {r['beforeMargin']:.0%} → {r['afterMargin']:.0%} | {'Controller approved' if r['id'] in approved else 'NOT approved'} | [{r['balanceEnd']}]({r['source']}) |")
lines += ['',
'ALSN uses June cash USD 399m and debt USD 4,114m, versus annual USD 1,495m and USD 2,921m. Normalized owner earnings stay USD 521m; the existing high-leverage margin becomes 50%. [Reviewed June 10-Q](https://www.sec.gov/Archives/edgar/data/1411207/000119312526334039/alsn-20260630.htm).','',
'FDJU uses June cash EUR 419.2m and debt EUR 2,211.7m, versus EUR 794.1m and EUR 2,261.7m. Its 35% requirement is unchanged. [Reviewed H1 results](https://www.fdjunited.com/wp-content/uploads/2026/07/20260729-FDJUNITEDpressrelease-H12026results.pdf). The vendor filing date is absent; the exported availability is explicitly the conservative 90-day fallback, not a claim about actual filing date.','',
'The additional transitions are supported here by the cached dated vendor balances, not newly completed independent issuer reviews. In particular, the large cash changes at ELV, Logista and PRDO warrant controller source/classification review before approval. FCN’s debt moves from USD 626.721m to USD 1,267.516m and invokes the existing moderate-leverage margin. No outcome-specific parameters were changed.','',
'**Full-corpus proof**','',
f"The full dereferenced copy contained 778,076 files / 54,730,820,086 bytes. The source head was `{audit['initialHead']}`. Copy audit: no missing files, size/mtime differences, shared live inodes or symlinks; the daily-runner lock was excluded. The unmodified ordinary publisher reproduces every one of the 3,899 released dossiers exactly, with 3,892 indexed records. All 2,079 historical-return caches are reused, with zero provider requests or cache failures.",'',
f"The final ordinary `publish --out ... --overwrite` examines all 3,899 dossiers. {summary['changedDossiers']:,} dossier valuation records change; {sum(r['beforeValue']!=r['afterValue'] for r in rows):,} mid-value numbers change (including unavailable results); {len(summary['changedPriceTests'])} price-test fields change; {len(flips)} Buy-now flags change. All 148 explicit freeze records remain identical. No unrelated dossier-field changes were found. All 1,529 eligible pre-change calculations reproduce their released baseline within numerical tolerance, with no changes to growth, discount rate, shares or tier in non-null corrected valuations.",'',
'Every affected dossier, including non-picks, has before/after values, verdict and price-test results, required margins, annual/current cash and debt, period, source link and availability assumption in [changed-valuations.csv](changed-valuations.csv). [changed-valuations.json](changed-valuations.json), [all-dossier-changes.json.gz](all-dossier-changes.json.gz) and [attribution.json](attribution.json) retain the full machine-readable evidence. Missing required current balance facts can leave a value unavailable; old cash/debt are not silently substituted.','',
'**Implementation**','',
'The analysis and historical-snapshot paths select the latest eligible dated balance independently of annual quality history and TTM flows. Publication also refreshes existing bound valuations so preserved coverage baselines do not retain annual cash indefinitely. Explicit verdict freezes remain binding. The source, period and actual/assumed availability travel with the valuation. TTM revenue supplies the operating cash reserve; current equity supplies tangible book; existing leverage thresholds remain unchanged.','',
'The reviewed Gamma H1 balance is retained. The dated, reusable pro-forma mechanism retains the reviewed Yum China scenario: USD 1.2bn bridge funds the USD 1.2bn purchase, USD 24m annual pretax financing cost, no assumed tax shield, licence savings or synergies. Availability respects both the base balance and closing disclosure; a later filed balance supersedes the scenario. Gamma is GBP 15.382742/share and Yum China USD 49.228415/share. The financing scenario remains explicitly approximate.','',
'Three defects found in the broader proof were corrected: interim debt now uses the existing same-statement component mapping; omitted quarterly lease obligations no longer erase an annual estimated TTM lease charge; refreshing a preserved valuation no longer repeats unrelated capitalization checks. Current lease observations replace the estimate when reported; otherwise the retained annual estimate is explicitly labelled. No Jev perimeter reader is imported or run. Historical caches and immutable forward records follow the ordinary publisher’s preservation rules.','',
'**Verification**','',
'- Final full unit suite: 240 files; 2,318 tests passed, one skipped. A 15-second per-test timeout accommodates host contention; no tests were excluded. Targeted red/green regressions cover dates, missing cash, component debt, tangible book, TTM leases/reserves, reviewed scenarios, preserved capitalization and exact approved transitions.','- All 3,899 candidate dossiers pass the consistency checks; the released baseline also has zero failures.','- TypeScript passed. The offline production build passed; the pages use the locally generated candidate through `VALUE_STORE_DIR`.','- ALSN and FDJU both render Wait, with buy-below prices USD 68.79 and EUR 19.49. API valuations match the candidate; valuation drawers open; zero page errors. Screenshots and browser receipt are retained.','- A direct invariant check against the completed output rejects `index/ES.json Buy-now changed 0 -> 1; prices and new dossiers explain at most +0/-0` (Logista).','- The REAL CLI path uses the pubfix-2 local bare-remote/stubbed-Blob harness, with only loopback networking and the source corpus mounted read-only. Environment loading is disabled. There is no `--force`, `--existing-analysis` or `--additions-only` bypass. SIGTERM interrupted earlier dry-run and real-path attempts; its cause was not established. The final ordinary output used a 1,536 MiB heap limit; a 1,024 MiB real-path attempt exhausted its V8 heap, so the final retry used 2,048 MiB.',
f"- Real publish exit: **{audit['realExit']}**. See [real-publish.log](real-publish.log) and [final-audit.json](final-audit.json). "+('The Buy-now invariant blocks before data commit, local push or Blob writes; successful real-path completion is NOT claimed.' if audit['realExit'] else 'The local publication completed.'),'',
'The real working tree and dry-run share identical bytes for every emitted JSON file. The strict whole-tree byte check is not green: the aborted real tree retains 25 additional legacy logo JSON files, each proved byte-identical to the pre-run baseline. These are not valuation changes. See [real-byte-proof.json](real-byte-proof.json) and [retained-logo-audit.json](retained-logo-audit.json).','',
'**Isolation and cleanup**','',
'No code push, external publication, external EODHD/Jev request, subagent or live daily-runner lock operation occurred. Source data head and verdict-freeze hash stayed fixed. All task-owned corpus copies, local bare remote, Blob files, temporary snapshots, baseline code and test home were deleted. The original corpus is retained.','',
'Procedural exception: the first unit run used existing tests that created and removed their own temporary directories under `homedir()/value-corpus`, before the test home was isolated. This violated the requested read-only boundary for those temporary directories. Subsequent suites used an isolated test home; no live research/publication-record change was observed. This is disclosed rather than claiming that no write of any kind occurred under the source path.','',
f"After cleanup: root {cleanup['freeBytes']['/']/1024**3:.2f} GiB; data {cleanup['freeBytes']['/Users/miki/data']/1024**3:.2f} GiB. Disk monitoring stayed above the 4 GiB stop floor throughout.",'',
'**Controller commands**','',
'```bash','cd ~/data/value-jev','git log -1 --oneline value-jev-2','git diff origin/master...value-jev-2 --stat','cat scripts/value/approved-verdict-changes.json','cat docs/value/jev-2/comparison.json','cat docs/value/jev-2/final-audit.json','```','',
'Reproduction is documented in [harness/README.md](harness/README.md). Do not run the live publisher while the additional transitions remain unapproved. Review each additional balance source and record an explicit controller decision before expanding the exact transition manifest. Then repeat the ordinary full-corpus output, real local publish, byte comparison and browser gates.','',
'**Complete price-test field changes**','',
'These are separate from the seven Buy-now flag changes above; a removed price test is shown as unavailable.','',
'| Dossier | Before | After |','|---|---|---|']
for r in summary['changedPriceTests']:lines.append(f"| {r['id']} | {r['before'] or 'unavailable'} | {r['after'] or 'unavailable'} |")
Path('docs/value/jev-2/report.md').write_text('\n'.join(lines)+'\n')
