import type { JevQuestion, SectionKey, TestKey } from "../types";

export const QUESTIONS_VERSION = "2";
export const QUESTIONS: Array<{
  id: string;
  version: string;
  test: Exclude<TestKey, "price">;
  label: string;
  sections: Array<SectionKey | "description">;
  mode: "any" | "mean";
  tag?: string;
  contradicts?: "yes" | "no";
  q: JevQuestion;
}> = [
  { id: "same_10y", version: "1", test: "understandable", label: "Core product likely to remain recognisable", sections: ["business", "description"], mode: "mean", contradicts: "no", q: { type: "noul", instructions: "Based on the business described, is the core product likely to remain recognisably the same in ten years? Judge product durability, without calculating or comparing dates." } },
  { id: "technology_change", version: "2", test: "understandable", label: "Exposure to technology change", sections: ["business", "risk", "description"], mode: "mean", q: { type: "score", instructions: "How exposed is the core product to being made obsolete by a new technology (not by regulation, demand shift or competition)? 0 = product stable for decades (utilities, consumer staples, cosmetics, mining); 1 = periodic tech shifts require ongoing reinvestment; 2 = a rival technology could replace the core product within a few years.", criteria: ["0: Stable for decades, such as utilities, consumer staples, cosmetics or mining", "1: Periodic technology shifts require reinvestment; gradual energy transition in oil and gas", "2: A rival technology could replace the core product within a few years"] } },
  { id: "commodity", version: "2", test: "understandable", label: "Revenue depends on commodity prices", sections: ["business", "risk", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Is the price the company receives for what it sells set mainly by a traded commodity market price (oil, metals, coal, power, memory chips), so that revenue moves with that price? Input-cost exposure, or carrying commodities as freight, does not count." } },
  { id: "government_dependence", version: "2", test: "understandable", label: "Revenue depends on government permission", sections: ["business", "risk", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Would revenue stop or be capped without a specific government licence, concession, charter or regulated tariff (bank, insurer, utility, spectrum, gaming)? Selling to government customers, general product regulation and subsidies do not count. A licence means legal permission to operate a business line, not patents or general product regulation." } },
  { id: "brand", version: "1", test: "moat", label: "Describes brand advantage", sections: ["business", "description"], mode: "any", tag: "brand", q: { type: "noul", instructions: "Does the text describe brand recognition or loyalty as a competitive advantage?" } },
  { id: "switching_costs", version: "1", test: "moat", label: "Describes switching costs", sections: ["business", "description"], mode: "any", tag: "switching_costs", q: { type: "noul", instructions: "Does the text describe customer switching costs as a competitive advantage?" } },
  { id: "network", version: "1", test: "moat", label: "Describes network effects", sections: ["business", "description"], mode: "any", tag: "network", q: { type: "noul", instructions: "Does the text describe a network effect in which additional users make the product more valuable to other users?" } },
  { id: "low_cost", version: "1", test: "moat", label: "Describes low-cost production", sections: ["business", "description"], mode: "any", tag: "low_cost", q: { type: "noul", instructions: "Does the text describe being a low-cost producer as a competitive advantage?" } },
  { id: "regulatory_moat", version: "2", test: "moat", label: "Describes regulatory protection", sections: ["business", "description"], mode: "any", tag: "regulatory_moat", q: { type: "noul", instructions: "Does the text say a government licence, franchise, charter, concession or permit (not a patent or trademark) restricts who may compete with the company? Answer NO for ordinary industry regulation, compliance burden or patent/data exclusivity. A regulatory licence is legal permission to operate a business line, not general product regulation." } },
  { id: "scale", version: "2", test: "moat", label: "Describes scale advantage", sections: ["business", "description"], mode: "any", q: { type: "noul", instructions: "Does the text explicitly say that the company's size or volume lowers its unit costs or gives purchasing, distribution or network advantages over smaller rivals? Merely being the largest or a leader, or listing store counts and revenues, is not enough." } },
  { id: "no_moat", version: "1", test: "moat", label: "No moat source described", sections: ["business", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does the text describe a business with none of these competitive advantages: brand, switching costs, network effects, low-cost production, regulatory licence or scale?" } },
  { id: "pricing_power", version: "1", test: "moat", label: "Describes pricing power", sections: ["business", "mdna", "letter", "description"], mode: "any", tag: "pricing_power", q: { type: "noul", instructions: "Does the prose explicitly state that the company raised prices without losing sales volume? Do not infer this by comparing numbers." } },
  { id: "commodity_product", version: "2", test: "moat", label: "Commodity product sold on price", sections: ["business", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Is the core product itself a standardized, undifferentiated commodity (for example a mined metal, oil, grain, bulk chemical) whose price the company cannot set? Answer NO for branded, contracted or service offerings even when the seller competes on price." } },
  { id: "revenue_model", version: "1", test: "economics", label: "Revenue model", sections: ["business", "description"], mode: "mean", tag: "recurring_revenue", q: { type: "choice", instructions: "Which revenue model best describes the business?", criteria: { recurring: "Contractual recurring revenue or subscriptions", repeat_consumable: "Consumable products bought repeatedly without a subscription", transactional: "Separate non-recurring transactions", project: "Bespoke projects or contracts", commodity: "Commodity production or trading" } } },
  { id: "capex_purpose", version: "1", test: "economics", label: "Capital expenditure purpose", sections: ["mdna", "capital"], mode: "mean", q: { type: "choice", instructions: "Does the prose describe capital expenditure as mostly maintenance or mostly growth? Do not calculate amounts.", criteria: { maintenance: "Mostly maintaining existing operations", growth: "Mostly expanding capacity or entering new markets" } } },
  { id: "admits_mistakes", version: "1", test: "management", label: "Letter admits a specific mistake", sections: ["letter"], mode: "any", tag: "admits_mistakes", q: { type: "noul", instructions: "Does management admit a specific mistake in this shareholder letter?" } },
  { id: "adjusted_metrics", version: "1", test: "management", label: "Letter leads with adjusted metrics", sections: ["letter"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does the shareholder letter lead with adjusted or non-GAAP metrics in its presentation of performance? Judge the prose, not the amounts." } },
  { id: "founder_led", version: "2", test: "management", label: "Founder or family ownership or board role", sections: ["business", "risk", "mdna", "letter", "capital", "compensation", "notes", "auditor", "description"], mode: "any", tag: "founder_led", q: { type: "noul", instructions: "Does the report state that a founder or founding family is a major shareholder or a director/chair today? Widely known ownership facts stated anywhere in the report count; do not infer ownership from the founding story alone. Do not calculate percentages or compare dates." } },
  { id: "compensation_basis", version: "1", test: "management", label: "Compensation incentives", sections: ["compensation"], mode: "mean", q: { type: "choice", instructions: "What does the prose say executive compensation rewards?", criteria: { per_share_value_or_returns: "Per-share value or returns on capital", size_or_revenue: "Company size or revenue" } } },
  { id: "buyback_below_value", version: "1", test: "management", label: "Buybacks described as below intrinsic value", sections: ["letter", "capital"], mode: "any", tag: "buyback_below_value", q: { type: "noul", instructions: "Does the text describe repurchasing shares below intrinsic value? Do not compare prices or calculate value." } },
  { id: "acquisition_led", version: "2", test: "management", label: "Acquisitions are the main growth strategy", sections: ["business", "letter", "capital", "description"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text say the company has grown mainly by buying other businesses (serial or transformative acquisitions), as opposed to organic growth with occasional deals? Answer YES if acquisitions are described as a core, recurring part of how it grows." } },
  { id: "material_weakness", version: "1", test: "accounting", label: "Material weakness in internal control", sections: ["notes", "auditor"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text disclose a material weakness in internal control?" } },
  { id: "auditor_changed", version: "1", test: "accounting", label: "Auditor change within the past three years disclosed", sections: ["auditor", "notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the prose explicitly state that the external auditor changed within the past three years? Require an explicit statement of that timeframe. Do not compare dates or calculate elapsed time." } },
  { id: "going_concern", version: "1", test: "accounting", label: "Going-concern uncertainty", sections: ["auditor", "notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text express material uncertainty or substantial doubt about the company's ability to continue as a going concern, rather than merely describing the going-concern accounting basis?" } },
  { id: "related_party", version: "2", test: "accounting", label: "Material related-party transactions", sections: ["notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Given the related-party note or Item 13, does the company report related-party transactions with named parties (affiliates, principal shareholders, executives' entities) of material size? Routine intercompany eliminations and compensation do not count." } },
];
