import type { JevQuestion, SectionKey, TestKey } from "../types";

export const QUESTIONS_VERSION = "1";
export const QUESTIONS: Array<{
  id: string;
  test: Exclude<TestKey, "price">;
  label: string;
  sections: Array<SectionKey | "description">;
  mode: "any" | "mean";
  tag?: string;
  contradicts?: "yes" | "no";
  q: JevQuestion;
}> = [
  { id: "same_10y", test: "understandable", label: "Core product likely to remain recognisable", sections: ["business", "description"], mode: "mean", contradicts: "no", q: { type: "noul", instructions: "Based on the business described, is the core product likely to remain recognisably the same in ten years? Judge product durability, without calculating or comparing dates." } },
  { id: "technology_change", test: "understandable", label: "Exposure to technology change", sections: ["business", "risk", "description"], mode: "mean", q: { type: "score", instructions: "How exposed is the business to technology making its core product obsolete?", criteria: ["Low exposure", "Medium exposure", "High exposure"] } },
  { id: "commodity", test: "understandable", label: "Revenue depends on commodity prices", sections: ["business", "risk", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does the described revenue model depend on commodity prices?" } },
  { id: "government_dependence", test: "understandable", label: "Revenue depends on government permission", sections: ["business", "risk", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does revenue depend on a government licence or regulation?" } },
  { id: "brand", test: "moat", label: "Describes brand advantage", sections: ["business", "description"], mode: "any", tag: "brand", q: { type: "noul", instructions: "Does the text describe brand recognition or loyalty as a competitive advantage?" } },
  { id: "switching_costs", test: "moat", label: "Describes switching costs", sections: ["business", "description"], mode: "any", tag: "switching_costs", q: { type: "noul", instructions: "Does the text describe customer switching costs as a competitive advantage?" } },
  { id: "network", test: "moat", label: "Describes network effects", sections: ["business", "description"], mode: "any", tag: "network", q: { type: "noul", instructions: "Does the text describe a network effect in which additional users make the product more valuable to other users?" } },
  { id: "low_cost", test: "moat", label: "Describes low-cost production", sections: ["business", "description"], mode: "any", tag: "low_cost", q: { type: "noul", instructions: "Does the text describe being a low-cost producer as a competitive advantage?" } },
  { id: "regulatory_moat", test: "moat", label: "Describes regulatory protection", sections: ["business", "description"], mode: "any", tag: "regulatory_moat", q: { type: "noul", instructions: "Does the text describe a regulatory licence that protects the business from competitors?" } },
  { id: "scale", test: "moat", label: "Describes scale advantage", sections: ["business", "description"], mode: "any", q: { type: "noul", instructions: "Does the text describe economies of scale as a competitive advantage?" } },
  { id: "no_moat", test: "moat", label: "No moat source described", sections: ["business", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does the text describe a business with none of these competitive advantages: brand, switching costs, network effects, low-cost production, regulatory licence or scale?" } },
  { id: "pricing_power", test: "moat", label: "Describes pricing power", sections: ["business", "mdna", "letter", "description"], mode: "any", tag: "pricing_power", q: { type: "noul", instructions: "Does the prose explicitly state that the company raised prices without losing sales volume? Do not infer this by comparing numbers." } },
  { id: "commodity_product", test: "moat", label: "Commodity product sold on price", sections: ["business", "description"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Is the described product a commodity sold primarily on price?" } },
  { id: "revenue_model", test: "economics", label: "Revenue model", sections: ["business", "description"], mode: "mean", tag: "recurring_revenue", q: { type: "choice", instructions: "Which revenue model best describes the business?", criteria: { recurring: "Contractual recurring revenue or subscriptions", repeat_consumable: "Consumable products bought repeatedly without a subscription", transactional: "Separate non-recurring transactions", project: "Bespoke projects or contracts", commodity: "Commodity production or trading" } } },
  { id: "capex_purpose", test: "economics", label: "Capital expenditure purpose", sections: ["mdna", "capital"], mode: "mean", q: { type: "choice", instructions: "Does the prose describe capital expenditure as mostly maintenance or mostly growth? Do not calculate amounts.", criteria: { maintenance: "Mostly maintaining existing operations", growth: "Mostly expanding capacity or entering new markets" } } },
  { id: "admits_mistakes", test: "management", label: "Letter admits a specific mistake", sections: ["letter"], mode: "any", tag: "admits_mistakes", q: { type: "noul", instructions: "Does management admit a specific mistake in this shareholder letter?" } },
  { id: "adjusted_metrics", test: "management", label: "Letter leads with adjusted metrics", sections: ["letter"], mode: "mean", contradicts: "yes", q: { type: "noul", instructions: "Does the shareholder letter lead with adjusted or non-GAAP metrics in its presentation of performance? Judge the prose, not the amounts." } },
  { id: "founder_led", test: "management", label: "Founder or family ownership or board role", sections: ["business", "compensation", "description"], mode: "any", tag: "founder_led", q: { type: "noul", instructions: "Does the text describe a founder or founding family as a large owner or a member of the board? Do not calculate ownership percentages." } },
  { id: "compensation_basis", test: "management", label: "Compensation incentives", sections: ["compensation"], mode: "mean", q: { type: "choice", instructions: "What does the prose say executive compensation rewards?", criteria: { per_share_value_or_returns: "Per-share value or returns on capital", size_or_revenue: "Company size or revenue" } } },
  { id: "buyback_below_value", test: "management", label: "Buybacks described as below intrinsic value", sections: ["letter", "capital"], mode: "any", tag: "buyback_below_value", q: { type: "noul", instructions: "Does the text describe repurchasing shares below intrinsic value? Do not compare prices or calculate value." } },
  { id: "acquisition_led", test: "management", label: "Acquisitions are the main growth strategy", sections: ["business", "letter", "capital", "description"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text describe acquisitions as the main growth strategy?" } },
  { id: "material_weakness", test: "accounting", label: "Material weakness in internal control", sections: ["notes", "auditor"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text disclose a material weakness in internal control?" } },
  { id: "auditor_changed", test: "accounting", label: "Auditor change within the past three years disclosed", sections: ["auditor", "notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the prose explicitly state that the external auditor changed within the past three years? Require an explicit statement of that timeframe. Do not compare dates or calculate elapsed time." } },
  { id: "going_concern", test: "accounting", label: "Going-concern uncertainty", sections: ["auditor", "notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text express material uncertainty or substantial doubt about the company's ability to continue as a going concern, rather than merely describing the going-concern accounting basis?" } },
  { id: "related_party", test: "accounting", label: "Material related-party transactions", sections: ["notes"], mode: "any", contradicts: "yes", q: { type: "noul", instructions: "Does the text describe material related-party transactions?" } },
];
