import {readFileSync,writeFileSync} from 'node:fs';
import {readCorpusJson} from '../../lib/value/corpus';
import type {FlagSource} from './stages/flags-fetch';
import type {Passage} from '../../lib/value/flags/extract';
const cases:Array<{id:string;company:string;topic:'signal'|'relationship';expected:string;counterparty?:string;evidence:Passage}>=[];
function add(company:string,expected:string,pattern:RegExp,counterparty?:string,index=0){
 const s=readCorpusJson<FlagSource>(`flags/sources/${company}.json`)!;
 const blocks=s.text.split(/\n\s*\n/);let found=blocks.filter(b=>b.length>80&&pattern.test(b))[index];
 if(found?.startsWith('•')){const at=blocks.indexOf(found),intro=blocks.slice(Math.max(0,at-10),at).reverse().find(b=>!b.startsWith('•')&&b.trim().endsWith(':'));if(intro)found=intro+'\n\n[…]\n\n'+found;}
 if(!found)throw Error(`${company}: no fixture ${pattern}`);
 cases.push({id:`${company}-${cases.length}`,company,topic:counterparty?'relationship':'signal',expected,counterparty,evidence:{quote:found.trim(),url:s.url,filed:s.filed,period:s.period,section:'Annual filing'}});
}
add('META.US','life_extended',/In January 2025, we completed/);
add('AMZN.US','life_shortened',/^Effective January 1, 2025 we changed/);
add('META.US','residual_guarantee',/residual value guarantees \(RVG\)/);
add('GOOGL.US','credit_backstop',/financial guarantees and credit derivatives with maximum/);
add('GOOGL.US','credit_backstop',/maximum potential amount of future payments under these guarantees/);
add('NVDA.US','third_party_guarantee',/We provided \$3.5 billion/);
add('NVDA.US','third_party_guarantee',/In fiscal year 2026, we entered into agreements to guarantee/);
add('KO.US','third_party_guarantee',/^As of December 31, 2025, we were contingently liable/);
add('ORCL.US','vendor_financing',/^We offer certain of our customers the option/);
add('NVDA.US','customer_concentration',/For fiscal year 2026, sales to one direct customer/);
add('CRWV.US','customer_concentration',/We recognized an aggregate of approximately 67%/);
add('QCOM.US','customer_concentration',/revenues from Apple, Samsung and Xiaomi each comprised/);
add('SWKS.US','customer_concentration',/^During fiscal 2025, fiscal 2024, and fiscal 2023, Apple/);
add('LULU.US','supplier_concentration',/^•Product manufacturing/);
add('LULU.US','supplier_concentration',/^•Fabrics/);
add('MSFT.US','related_party',/As an equity method investee, OpenAI is a related party/);
add('CRWV.US','material_weakness',/^We have identified material weaknesses/);
add('LUCKIN.2019','material_weakness',/^Prior to this offering, we have been a private company/);
add('VALEANT.2015','material_weakness',/^Based on the results of the AHC Review/);
for(const company of ['GOOGL.US','AAPL.US','NVDA.US','KO.US','QCOM.US','LULU.US','AMD.US','AVGO.US','SWKS.US'])add(company,'none',/assessing the risk that a material weakness exists/);
add('NVDA.US','none',/We are finalizing an investment and partnership agreement with OpenAI/);
add('SWKS.US','none',/The Company has made no significant contractual guarantees/);
add('ORCL.US','none',/^Goodwill represents the excess/);
add('GOOGL.US','none',/^We assess the reasonableness of the useful lives/);
add('META.US','none',/^We cannot guarantee that our share repurchase program/);
add('LULU.US','none',/information required by this item is incorporated by reference.*Related Party Transactions/);
add('NVDA.US','supplier',/We utilize foundries, such as Taiwan Semiconductor/,'Taiwan Semiconductor');
add('NVDA.US','supplier',/We utilize foundries, such as Taiwan Semiconductor/,'Samsung');
add('NVDA.US','supplier',/We purchase memory from SK Hynix/,'SK Hynix');
add('NVDA.US','supplier',/We purchase memory from SK Hynix/,'Micron Technology');
add('CRWV.US','customer',/We recognized an aggregate of approximately 67%/,'Microsoft');
add('CRWV.US','customer',/^Although we currently generate the majority/,'OpenAI');
add('CRWV.US','customer',/^Although we currently generate the majority/,'Meta');
add('SWKS.US','customer',/^During fiscal 2025, fiscal 2024, and fiscal 2023, Apple/,'Apple');
add('QCOM.US','customer',/revenues from Apple, Samsung and Xiaomi each comprised/,'Apple');
add('QCOM.US','customer',/revenues from Apple, Samsung and Xiaomi each comprised/,'Samsung');
add('QCOM.US','customer',/revenues from Apple, Samsung and Xiaomi each comprised/,'Xiaomi');
add('AMZN.US','stake',/^As of December 31, 2025, our recorded value in equity/,'Anthropic');
add('AMZN.US','stake',/^As of December 31, 2025, our recorded value in equity/,'Rivian');
add('MSFT.US','stake',/As an equity method investee, OpenAI is a related party/,'OpenAI');
add('NVDA.US','none',/We are finalizing an investment and partnership agreement with OpenAI/,'OpenAI');
add('NVDA.US','none',/large cloud services companies with internal teams/,'Microsoft');
add('NVDA.US','none',/large cloud services companies with internal teams/,'Amazon');
add('NVDA.US','none',/large cloud services companies with internal teams/,'Alphabet');
add('META.US','none',/Carreyrou et al. v. Anthropic/,'Anthropic');
add('META.US','none',/each of Apple and Google have integrated competitive products/,'Apple');
add('META.US','none',/each of Apple and Google have integrated competitive products/,'Google');
for(const company of ['AAPL.US','QCOM.US','SWKS.US','GOOGL.US'])add(company,'none',/assessing the risk that a material weakness exists/,'OpenAI');
cases.push(...JSON.parse(readFileSync('tests/fixtures/value/flags/additional-calibration.json','utf8')));
writeFileSync('tests/fixtures/value/flags/calibration.json',JSON.stringify({description:'Manually labelled actual filing passages. Historical Luckin IPO and Valeant disclosures included; accuracy is fixture performance, not a claim of universal recall.',cases},null,2)+'\n');
console.log(cases.length,'labelled cases');
