import { MethodRules } from '@/components/value/MethodRules';
import { ValueLink } from '@/components/value/ValueLink';
import { T } from '@/lib/value/config';
export default function Method() {
 return <article className="method-page"><ValueLink href="/">← All companies</ValueLink><h1>5 quality tests + price. Every assumption visible.</h1><p>We assess business quality from financial statements and filing evidence, then compare a conservative estimate of value with the market price. Each test stands on its own; there is no blended score.</p>{[
 ['understandable','Understandable',`At least ${T.understandable.years} years of history, few revenue declines or loss years, and stable operating margins. Financial companies use a separate template.`],
 ['moat','Moat',`Operating companies need a median return on invested capital of at least ${T.moat.roicMedian*100}%. ROIC divides after-tax operating profit by invested capital. Invalid or non-positive denominators are not meaningful. Banks and insurers use return on tangible equity (net income divided by equity excluding goodwill and intangibles), not return on total equity.`],
 ['economics','Economics','Owner earnings start with net income, add depreciation and amortisation, then subtract estimated maintenance capital spending and stock compensation. Valuation uses the five- or seven-year normalised window disclosed in the dossier; annual charts show individual fiscal years. These are different windows and are labelled accordingly.'],
 ['management','Management','Share counts, retained earnings and market value creation indicate how managers allocate capital. The $1 test compares market value gained with cumulative retained earnings. Financial companies use book-value measures where appropriate.'],
 ['accounting','Accounting','Accruals compare accounting profit with operating cash flow relative to assets. Receivables, stock compensation, restructuring and acquisition events provide additional checks. Missing inputs stay visible.'],
 ['price','Price and value','Owner earnings are projected for ten years plus a terminal value, discounted at a required return, adjusted for net cash and divided by diluted shares. Banks and insurers use book value and normalised ROE. The first ten years use the company-specific growth estimate. Terminal growth represents a separate mature-economy assumption and can exceed a depressed near-term growth rate; this assumption is explicit, not a forecast. Low, mid and high values are scenarios, not statistical confidence intervals. Equal scenarios are labelled together.'],
 ].map(([id,title,copy])=><section id={id} key={id}><h2>{title}</h2><p>{copy}</p></section>)}<h2>Required discount</h2><p>The buy price is the central estimated value less a discount of {Object.values(T.price.requiredMos).map(n=>`${n*100}%`).join(', ')}, depending on earnings stability. Price below mid but above the buy price is “Wait”. Price/value uses a logarithmic scale; lower is cheaper. Positive margin of safety means the percentage below mid value.</p><h2>Who sets the rules?</h2><p>GigaInvestors is an independent site. These numerical thresholds are our way to apply Buffett-inspired principles, not rules endorsed by Warren Buffett. “Buffett’s bar” means this site’s chosen cutoff. The $1 retained-earnings test follows his stated principle; other cutoffs are model choices.</p><MethodRules/><h2>Sources and uncertainty</h2><p>Open data comes from EODHD, SEC EDGAR, Japan’s EDINET and European ESEF filings. The dossier links to the source filing. Reference prices derived from market capitalisation are identified separately from closes. Machine-read qualitative signals remain informational until verified. Extracted quotations are withheld without an explicit supporting-evidence classification.</p><p>History uses current restated data and the surviving covered universe; delisted and missing companies are not reconstructed. Returns exclude dividends, are not annualised, and overlapping yearly cohorts are not an investable portfolio. Debt, cyclicality and currency movements can materially alter outcomes.</p><p>Estimates depend on assumptions and are not guarantees or investment advice.</p><p><a href="https://www.sec.gov/edgar/search/">SEC EDGAR ↗</a> · <a href="https://eodhd.com/">EODHD ↗</a></p></article>;
}
