import { METHOD_TESTS } from '@/lib/value/method-content';
import { MethodChanges } from '@/components/value/MethodChanges';
import { HindsightSimulation } from '@/components/value/HindsightSimulation';
import { readStore } from '@/lib/value/store';
import type { HistoryIndex } from '@/lib/value/time-travel';
import { MethodRules } from '@/components/value/MethodRules';
import { ValueLink } from '@/components/value/ValueLink';
import { T } from '@/lib/value/config';
export default async function Method() {
 const history=await readStore<HistoryIndex>('history/index.json');
 return <article className="method-page"><ValueLink href="/">← All companies</ValueLink><h1>5 quality tests + price. Every assumption visible.</h1><p>We assess business quality from financial statements and filing evidence, then compare a conservative estimate of value with the market price. Each test stands on its own; there is no blended score.</p>{METHOD_TESTS.map(([id,title,copy])=><section id={id} key={id}><h2>{title}</h2><p>{copy}</p></section>)}<h2>Required discount</h2><p>The buy price is the central estimated value less a discount of {Object.values(T.price.requiredMos).map(n=>`${n*100}%`).join(', ')}, depending on earnings stability. Durable compounders use 15%; elevated leverage can raise that to 35% or 50%. Price below mid but above the buy price is “Wait”. Next closest uses a linear distance from the buy price; lower is cheaper. Companies below that price must also meet the expected return hurdle to qualify for Buy now.</p><h2>Who sets the rules?</h2><p>GigaInvestors is an independent site. These numerical thresholds are our way to apply Buffett-inspired principles, not rules endorsed by Warren Buffett. “Buffett’s bar” means this site’s chosen cutoff. The $1 retained-earnings test follows his stated principle; other cutoffs are model choices.</p><MethodChanges/><MethodRules/><HindsightSimulation history={history}/><h2>Sources and uncertainty</h2><p>Open data comes from EODHD, SEC EDGAR, Japan’s EDINET and European ESEF filings, supplemented by annual Yahoo fundamentals. The dossier links to the source filing. Reference prices derived from market capitalisation are identified separately from closes. Machine-read qualitative signals are informational. Extracted quotations are withheld without an explicit supporting-evidence classification.</p><p>The site covers companies in the selected major stock-market indexes. Western markets and Show all markets both operate within that universe. History uses today’s index membership, not membership at the historical date, creating survivorship bias. History uses current restated data and the surviving covered universe; delisted and missing companies are not reconstructed. Returns exclude dividends, are not annualised, and overlapping yearly cohorts are not an investable portfolio. Debt, cyclicality and currency movements can materially alter outcomes.</p><p>Estimates depend on assumptions and are not guarantees or investment advice.</p><p><a href="https://www.sec.gov/edgar/search/">SEC EDGAR ↗</a> · <a href="https://eodhd.com/">EODHD ↗</a></p></article>;
}
