import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import * as edinet from "../../../lib/value/japan/edinet";
import japan from "../../../scripts/value/stages/japan";
import { appendJsonl, readCorpusJson, readJsonl, writeCorpusJson } from "../../../lib/value/corpus";
import type { Company, Fundamentals, ReportMeta } from "../../../lib/value/types";
const fixture=path.resolve('tests/fixtures/value/edinet');
const data=JSON.parse(readFileSync(path.join(fixture,'documents-2025-06-18.json'),'utf8'));
const doc=edinet.annualReportDocuments(data).find(d=>d.secCode==='80580')!;
let dir:string;
beforeEach(()=>{dir=mkdtempSync(path.join(tmpdir(),'japan-stage-'));vi.stubEnv('VALUE_CORPUS_DIR',dir);vi.stubEnv('EDINET_API_KEY','offline-key');vi.stubGlobal('fetch',()=>{throw new Error('network forbidden')});vi.spyOn(console,'log').mockImplementation(()=>{});});
afterEach(()=>{rmSync(dir,{recursive:true,force:true});vi.restoreAllMocks();vi.unstubAllEnvs();vi.unstubAllGlobals();});
it('writes gated fundamentals, EDINET sections and primary identity; resumes without downloads',async()=>{
  vi.spyOn(edinet,'annualReports').mockResolvedValue([doc]);
  const download=vi.spyOn(edinet,'downloadCsv').mockResolvedValue(readdirSync(path.join(fixture,'mitsubishi-csv')).map(file=>readFileSync(path.join(fixture,'mitsubishi-csv',file),'utf16le')));
  appendJsonl('universe.jsonl',{id:'MSBHF.US',code:'MSBHF',exchange:'US',country:'US',name:'Mitsubishi Corporation',currency:'USD',listings:['MSBHF.US'],source:'eodhd',marketCapUsd:1e9});
  await japan({});
  const universe=readJsonl<Company>('universe.jsonl');expect(universe).toHaveLength(1);expect(universe[0]).toMatchObject({id:'8058.JP',currency:'JPY',source:'edinet',listings:['8058.JP','MSBHF.US']});
  expect(readCorpusJson<Fundamentals>('fundamentals/8058.JP.json')?.integrity).toMatchObject({ok:false,reasons:['fewer than 7 annual periods']});
  expect(readCorpusJson<ReportMeta>('reports/8058.JP/meta.json')).toMatchObject({kind:'EDINET',filed:'2025-06-18',period:'2025-03-31'});
  download.mockRejectedValue(new Error('cached documents must not download'));
  await japan({});expect(readJsonl('universe.jsonl')).toEqual(universe);
  expect(readCorpusJson('raw/edinet/merged-listings.json')).toEqual([{from:'MSBHF.US',to:'8058.JP'}]);
});
it('does not cache API error payloads or leak the API key in errors',async()=>{
  vi.stubGlobal('fetch',async()=>new Response(JSON.stringify({metadata:{status:'403'}})));
  await expect(edinet.listDocuments('2025-06-18')).rejects.toThrow('invalid response');
  vi.stubGlobal('fetch',async()=>{throw new Error('offline-key')});
  await expect(edinet.listDocuments('2025-06-18')).rejects.toThrow('EDINET documents.json: request failed');
});
it('retains EDINET companies and ADR aliases through a later EODHD universe refresh',async()=>{
  const { retainJapaneseCompanies } = await import('../../../lib/value/japan/companies');
  const home={id:'8058.JP',code:'8058',exchange:'JP',country:'JP',currency:'JPY',name:'三菱商事',listings:['8058.JP','MSBHF.US'],source:'edinet'} as Company;
  appendJsonl('universe.jsonl',home);
  writeCorpusJson('raw/edinet/issuers/8058.JP.json',{issuer:{company:home,englishName:'Mitsubishi Corporation'}});
  const refreshed={...home,id:'MSBHF.US',code:'MSBHF',exchange:'US',currency:'USD',name:'Mitsubishi Corporation',listings:['MSBHF.US'],source:'eodhd'} as Company;
  expect(retainJapaneseCompanies([refreshed])).toEqual([home]);
});
