vi.mock('@/scripts/value/blob-publish',()=>({uploadPublishedSnapshot:vi.fn(async()=>({}))}));
import {uploadPublishedSnapshot} from '@/scripts/value/blob-publish';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { appendJsonl } from '@/lib/value/corpus';
import { bulkLastDay, callsUsedToday } from '@/lib/value/eodhd';
import { yahooPrice } from '@/lib/value/prices-yahoo';
import prices from '@/scripts/value/stages/prices';
import { pushRepository } from '@/scripts/value/stages/publish';
vi.mock('@/lib/value/eodhd',()=>({bulkLastDay:vi.fn(),callsUsedToday:vi.fn()}));
vi.mock('@/lib/value/prices-yahoo',()=>({yahooPrice:vi.fn()}));
vi.mock('@/scripts/value/stages/publish',()=>({withPublishRepository:async(run: (repo:string)=>Promise<void>)=>run(process.env.VALUE_CORPUS_DIR!),git:vi.fn(()=>''),pushRepository:vi.fn()}));
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'prices-stage-'));vi.stubEnv('VALUE_CORPUS_DIR',root);vi.mocked(callsUsedToday).mockResolvedValue(1);vi.mocked(yahooPrice).mockRejectedValue(new Error('Unavailable'));mkdirSync(join(root,'index'));});
afterEach(()=>{rmSync(root,{recursive:true,force:true});vi.unstubAllEnvs();vi.resetAllMocks();});
it.each([1,2])('publishes successful quotes before setting stage outcome at 95 percent (%s missing)',async missing=>{
 const companies=Array.from({length:20},(_,i)=>({id:`C${i}.US`,code:`C${i}`,exchange:'US',country:'US',source:'eodhd'}));
 for(const company of companies)appendJsonl('universe.jsonl',company);
 appendJsonl('universe.jsonl',{id:'NOT-PUBLISHED.NSE',exchange:'NSE'});
 writeFileSync(join(root,'index/US.json'),JSON.stringify(companies));
 const date=new Date().toISOString().slice(0,10);
 vi.mocked(bulkLastDay).mockResolvedValue(companies.slice(missing).map(c=>({code:c.code,close:10,date})));
 if(missing===1)await expect(prices({})).resolves.toBeUndefined();
 else await expect(prices({})).rejects.toThrow('below 95%');
 expect(Object.keys(JSON.parse(readFileSync(join(root,'prices/US.json'),'utf8')))).toHaveLength(20-missing);
 const runs=readdirSync(join(root,'prices-runs'));expect(JSON.parse(readFileSync(join(root,'prices-runs',runs[0]),'utf8'))).toMatchObject({total:20,fresh:20-missing,ok:missing===1});
 expect(pushRepository).toHaveBeenCalledOnce();
 expect(uploadPublishedSnapshot).toHaveBeenCalledWith(root);
 expect(vi.mocked(uploadPublishedSnapshot).mock.invocationCallOrder[0]).toBeGreaterThan(vi.mocked(pushRepository).mock.invocationCallOrder[0]);
 expect(bulkLastDay).toHaveBeenCalledTimes(1);
});
