import {expect,it} from 'vitest';
import {readFileSync,readdirSync} from 'node:fs';
import {buildOutput} from '@/lib/value/build-output';
import {publishBalances} from '@/scripts/value/publish-balances';
import {valueCompany} from '@/lib/value/valuation';
import {shardOf} from '@/lib/value/shard';
import {makeYears} from './synthetic';
import type {Analysis} from '@/lib/value/types';
const base=readdirSync('tests/fixtures/value/store/dossiers').flatMap(f=>Object.values(JSON.parse(readFileSync(`tests/fixtures/value/store/dossiers/${f}`,'utf8')))).find((a:any)=>a.id==='KO.US') as Analysis;
it('reprices bound research without reopening an unrelated capitalization check',()=>{
 const years=makeYears({from:2015}),a=structuredClone(base);
 a.valuation=valueCompany({years,kind:'operating',currency:'USD',bondYield:.04,cyclical:false}).valuation;
 a.company.marketCapUsd=null;a.company.currency='USD';a.requiredMos=.25;
 const prices={'KO.US':[100,'2026-10-05'] as [number,string]};
 const {files}=buildOutput({analyses:[a],prices,fx:{USD:1},holdersByTicker:{},investorNames:{}});
 const key=`dossiers/${shardOf(a.id)}.json`,d=(files[key] as any)[a.id];
 expect(d.valuation).not.toBeNull();d.company.marketCapUsd=1;
 const raw={General:{CurrencyCode:'USD'},Financials:{Balance_Sheet:{quarterly:{'2026-06-30':{filing_date:'2026-08-01',cash:40,shortLongTermDebtTotal:700}}}}};
 const read=(p:string):any=>p==='verdict-freeze.json'?{ids:[]}:p.startsWith('fundamentals/')?{years}:p.startsWith('analysis/inputs/')?{memoYears:years}:p.startsWith('raw/')?raw:null;
 const quality=structuredClone(d.tests),company=structuredClone(d.company);
 publishBalances(files,prices,{},read);
 const next=(files[key] as any)[a.id];
 expect(next.valuation).not.toBeNull();expect(next.valuation.netDebt).toBe(660);
 expect(next.company).toEqual(company);
 for(const k of Object.keys(quality).filter(k=>k!=='price'))expect(next.tests[k]).toEqual(quality[k]);
 const frozen=structuredClone(files);
 publishBalances(files,prices,{},p=>p==='verdict-freeze.json'?{ids:['KO.US']}:read(p));
 expect(files).toEqual(frozen);
});
it('replaces a cached valuation based on a partial quarter with the complete annual balance',async()=>{
 const {refreshBalanceValuation}=await import('@/lib/value/refresh-balance-valuation');
 const years=makeYears({from:2015}),a=structuredClone(base);
 a.valuation=valueCompany({years,kind:'operating',currency:'USD',bondYield:.04,cyclical:false}).valuation!;
 a.valuation.balanceSheet={end:'2026-06-30',filed:'2026-08-01',source:'partial cached quarter',basis:'filed'};
 const raw={General:{CurrencyCode:'USD'},Financials:{Balance_Sheet:{quarterly:{'2026-06-30':{filing_date:'2026-08-01',cash:40}}}}};
 const read=(p:string):any=>p.startsWith('fundamentals/')?{years}:p.startsWith('analysis/inputs/')?{memoYears:years}:p.startsWith('raw/eodhd/')?raw:null;
 const next=refreshBalanceValuation(a,read,'2026-10-06');
 expect(next.valuation?.balanceSheet?.end).toBe('2025-12-31');expect(next.valuation?.netDebt).toBe(0);
});
