from pathlib import Path
import json,runpy
R=Path(__file__).resolve().parents[2];O=R/'research/rules/outputs'
runpy.run_path(str(R/'research/rules/report-final.py'))
p=R/'research/rules/rules-1-report.md';s=p.read_text()
sem=json.loads((O/'browser/semantics.json').read_text());layout=json.loads((O/'browser-layout/report.json').read_text());cleanup=json.loads((O/'cleanup.json').read_text())
quality=sum(len(r.get('tests',[])) for r in sem)
assert quality == 20 and len(sem) == 10
assert all('price math: expected' in r.get('error','') for r in sem)
assert cleanup['archive_verified'] and cleanup['local_server_stopped']
assert all(not Path(p).exists() for p in cleanup['removed'])
receipt={'overall':'NOT','method':'3.5.0','units':{'files_passed':239,'tests_passed':2336,'skipped':1},'build':'PASS','frozen_numeric_ship_gates':'PASS','ordinary_publish':{'baseline_exit':1,'candidate_exit':1,'final_error':'Publish invariant: invalid issuer alias RACE.US -> RACE.MI','copy_only_filing_holds':6},'comparison':{'exposed_company_quality_changes':181,'proposed_numeric_changes':190,'all_quality_gained':24,'all_quality_lost':31,'buys_gained':['001800.KO'],'buys_lost':['000786.SHE','FDJU.PA','INMD.US','IPS.PA'],'all_28_buys_pass_production_price_gate':True},'browser':{'companies':['NVDA.US','EME.US','MRK.US','RHM.XETRA','IPS.PA'],'viewports':['1728x970','390x844'],'quality_surface_checks_passed':quality,'price_surface_checks_failed':sum(not r['pass'] for r in sem),'layout_states_failed':sum(bool(r['issues']) for r in layout),'layout_states':len(layout)},'cleanup':cleanup,'corpus_constraint_incident':{'description':'Existing unit fixtures created temporary directories under the real corpus before setting their fixture corpus environment. Five test files now use a separate temporary parent; final units and server use filesystem/network guards.','verified_leftover':'/Users/miki/value-corpus/fundamentals-test-Xxanes','cleanup_approval_received':False,'leftover_removed':False},'restrictions':{'subagents':False,'push':False,'remote_publication':False,'eodhd_data_acquisition':False,'daily_runner_lock_touched':False}}
(O/'final-verification.json').write_text(json.dumps(receipt,indent=2)+'\n')
verification=f'''- Full unit suite: **239 files passed; 2,336 tests passed, one skipped**. Final command: isolated test corpus/temp parent, outbound/live-corpus mutation guard, `npm test -- --maxWorkers=1 --testTimeout=15000`. The longer timeout is for subprocess-heavy fixtures on the shared host. Provider requests are mocked; real outbound sockets are blocked.
- Final production build: **PASS**, `npm run build -- --webpack`, local candidate store, two build workers, 1.5 GiB heap. Compilation, TypeScript and 222 static pages completed. No secrets were supplied or printed.
- Frozen-source parity, 93,961 paired replay invariants and baseline portfolio parity: **PASS**. No other three quality verdicts change between candidates; raw risk series and price requirements remain intact.
- Current price gate: **PASS for all 28 buys**, including the new buy tested without any legacy price freeze. All existing explicit frozen dossiers are unchanged. Prior dated forward records, price files and historical observations match between arms; only historical method-version metadata and the new local-only 2026-10-06 forward record differ.
- Ordinary `publish --out`: **FAIL in both arms**, despite writing 3,897 dossier records and 3,889 indexed companies. Both finish with `invalid issuer alias RACE.US -> RACE.MI`. Six additional holds were applied only to the disposable copy after the earlier full-filing refusal. No publisher invariant, filing requirement or production freeze was weakened. A shared retired-history-identity repair was applied in both arms; its failing/passing test is retained.
- Five-company browser gate: **FAIL overall**. The changed Understandable/Moat tile, drawer, series, table, threshold and verdict comparisons pass **{quality}/20** across desktop and mobile. The price-surface check fails **10/10** because `app/unified.css` hides `.valuation-math` on unified company pages; this is absent visible price math, not a failed computational buy gate. The unchanged broad layout audit fails **70/90** states, including 12px controls/navigation and excess drawer whitespace. The harness now waits for visible drawer content and detachment; transient early-capture failures are not treated as final product results. Screenshots and full captures are retained in `outputs/browser` and `outputs/browser-layout`.
- The exact released-snapshot→3.4.0 control comparison has **112 index mask/buy/coverage differences**. These are recorded separately in `publication-proof.json`, not attributed to 3.5.0. Full paired dossier field differences are retained in `publication-field-diffs.json.gz`.
- Cleanup: disposable corpus, engine archives, analysis backups, local exports, test fixtures and `.next` build output deleted. The local browser server was stopped. Derived evidence is retained as a verified archive of **20,264 records**, with its SHA-256 manifest, CSVs, report and screenshots.
- Read-only violation: initial unit fixtures created temporary directories under the real corpus. The verified leftover is `/Users/miki/value-corpus/fundamentals-test-Xxanes`. Its narrow cleanup was requested because the user's read-only instruction prohibits further live-corpus writes; no approval arrived, so it remains untouched. No actual company-data rewrite or runner-lock operation was performed by this task. Do not describe the run as fully read-only.

Before READY: resolve the canonical filing/alias publication blockers through their normal evidence process and repair the shared price-display/layout gate, then rerun an unqualified ordinary export and browser gate. Lovisa/Ipsen's abrupt reported gross-margin shifts also warrant primary-statement verification. The two rule parameters remain frozen; none of these failures justify tuning them on later returns.

Evidence directory: `/Users/miki/data/value-rules/research/rules/outputs`. The branch work and report are committed locally with the requested commit message; no push or remote publication was performed.'''
old='Verification receipts are under `research/rules/outputs`: frozen-source and replay invariants (`verification.json`), price gate (`price-gate-proof.json`), ordinary publish logs, full unit log, build log and browser receipts. Final operational status and cleanup receipt are appended below.'
assert old in s;s=s.replace(old,verification)
s=s.replace('Overall readiness is NOT:', 'Overall readiness is NOT: the five-company browser gate fails on hidden price calculations and shared layout issues;',1)
s=s.replace('Method 3.5.0 now judges', 'NVDA now passes all five quality tests and still fails the price test. Method 3.5.0 now judges',1)
p.write_text(s);Path('/Users/miki/GitHub/superinvestors-wt/value/.superpowers/sdd/2026-09-29-value/rules-1-report.md').write_text(s)
print('Final report: NOT; quality checks',quality,'/20; ordinary publish and browser gates failed')
