import type { Id } from "./types";

export const CALIBRATION: Array<{ id: Id; expect: "quality" | "not_quality" | "exception"; why: string }> = [
  { id: "KO.US", expect: "quality", why: "Brand and repeat purchases" },
  { id: "AAPL.US", expect: "quality", why: "Brand and ecosystem switching costs" },
  { id: "AXP.US", expect: "quality", why: "Payment network and customer loyalty" },
  { id: "MCO.US", expect: "quality", why: "Ratings franchise and regulatory barriers" },
  { id: "VRSN.US", expect: "quality", why: "Domain registry franchise" },
  { id: "V.US", expect: "quality", why: "Payment network scale" },
  { id: "MA.US", expect: "quality", why: "Payment network scale" },
  { id: "CB.US", expect: "quality", why: "Insurance underwriting discipline" },
  { id: "DPZ.US", expect: "quality", why: "Brand and franchise economics" },
  { id: "POOL.US", expect: "quality", why: "Distribution scale and recurring maintenance demand" },
  { id: "CHTR.US", expect: "quality", why: "Broadband infrastructure and recurring revenue" },
  { id: "8058.JP", expect: "quality", why: "Diversified trading house and capital allocation" },
  { id: "8031.JP", expect: "quality", why: "Diversified trading house and capital allocation" },
  { id: "8001.JP", expect: "quality", why: "Diversified trading house and capital allocation" },
  { id: "8002.JP", expect: "quality", why: "Diversified trading house and capital allocation" },
  { id: "8053.JP", expect: "quality", why: "Diversified trading house and capital allocation" },
  { id: "DAL.US", expect: "not_quality", why: "Airline cyclicality and capital intensity" },
  { id: "UAL.US", expect: "not_quality", why: "Airline cyclicality and capital intensity" },
  { id: "AAL.US", expect: "not_quality", why: "Airline cyclicality and capital intensity" },
  { id: "LUV.US", expect: "not_quality", why: "Airline cyclicality and capital intensity" },
  { id: "JBLU.US", expect: "not_quality", why: "Airline cyclicality and capital intensity" },
  { id: "GT.US", expect: "not_quality", why: "Cyclical manufacturing and capital intensity" },
  { id: "NCLH.US", expect: "not_quality", why: "Cruise line losses and heavy dilution" },
  { id: "FCX.US", expect: "not_quality", why: "Commodity copper exposure" },
  { id: "VALE.US", expect: "not_quality", why: "Commodity iron ore exposure" },
  { id: "CLF.US", expect: "not_quality", why: "Commodity steel pricing" },
  { id: "AA.US", expect: "not_quality", why: "Commodity aluminium exposure" },
  { id: "BHC.US", expect: "not_quality", why: "Serial acquisition and leverage risk" },
  { id: "PLUG.US", expect: "not_quality", why: "Losses and dilution risk" },
  { id: "AMC.US", expect: "not_quality", why: "Losses and dilution risk" },
  { id: "LCID.US", expect: "not_quality", why: "Losses and dilution risk" },
  { id: "RIVN.US", expect: "not_quality", why: "Losses and dilution risk" },
  { id: "CCL.US", expect: "not_quality", why: "Cruise line losses and heavy dilution" },
  { id: "M.US", expect: "not_quality", why: "Department store competition and weak pricing power" },
  { id: "OXY.US", expect: "exception", why: "Expected to fail moat; Berkshire holds on price or a commodity thesis" },
  { id: "CVX.US", expect: "exception", why: "Expected to fail moat; Berkshire holds on price or a commodity thesis" },
];
