/** New rule changes get a new entry; published forward observations are never restated. */
export const METHOD_CHANGES = [
  { version: '3.7.1', date: '2026-10-08', changelog: 'Buy verdicts follow the data: no approval manifest, and an unapproved Buy change no longer keeps the old published record. Corrects vendor statement inputs against issuer filings (IPS.PA, 000786.SHE, SIQ.AU, 300760.SHE, 600519.SHG, 0700.HK). Reviewed distinct issuers use the SEC ticker-map CIK, and another issuer\'s filing text or XBRL facts are excluded and flagged instead of failing the company. Calibration, evidence coverage, identity, share and publication-receipt guards are unchanged. Every verdict change is logged with its cause. The 3.7.0 rules are unchanged. These fixes were reviewed as 3.6.1, which never published.' },
  { version: '3.7.0', date: '2026-10-08', changelog: 'Buffett/Munger evolution review from primary sources: rename the numeric understandability screen as earnings resilience because circle of competence is investor-specific; replace the operating-company $1 retained-earnings verdict with per-share economic progress, keeping the old market-dollar calculation only as context. The risk-free discount-rate candidate was tested and not shipped because it breached the owner performance veto; valuation rates and safety discounts remain as model choices.' },
  { version: '3.6.0', date: '2026-10-07', changelog: 'Owner-authorized correctness override: charge stock compensation once, and value every operating business at its five-year median owner-earnings margin times current annual or complete TTM revenue. Keep loss years, revenue-decline override and cyclical discounts; financial and NAV methods remain separate. TTM maintenance uses annual capacity context. Historical returns are reported per correction, not a release veto; unapproved Buy flips retain complete published records. Cash-conversion presentation remains based on five-year totals.' },
  { version: '3.5.0', date: '2026-10-06', changelog: 'Judge the record, not one bad year: one fully recovered positive operating-margin dip can meet the existing variation bar; gross-margin resilience compares recent and typical margins instead of permanently anchoring to FY2023. Raw variability, capital-return thresholds, financial tests, valuation and price gates remain unchanged.' },
  { version: '3.4.0', date: '2026-10-05', changelog: 'Understandable margins may improve steadily: positive, loss-free histories can pass with a monotone rise or a dominant upward trend. Other quality and price thresholds, financial tests, verdict freezes and LTM confirmation are unchanged.' },
  { version: '3.3.0', date: '2026-10-04', changelog: 'Quarterly LTM; two-quarter confirmation.' },
  { version: '3.2.0', date: '2026-10-01', changelog: 'Expected return solves the same valuation cash flows; applied quality rules are explicit; capex flags require lagging earnings and goodwill uses assets.' },
  { version: '3.1.0', date: '2026-10-01', changelog: 'Evidence-backed judgement (e.g. growth capex), business section, materiality-sized red and green flags.' },
  { version: '3.0.0', date: '2026-10-01', changelog: 'Live index universe, valuation v2, financial tests, completeness requirements and thesis check.' },
] as const;
export const METHOD_VERSION = METHOD_CHANGES[0].version;
