import {VALUE_PRODUCT_NAME} from './brand';
import {T} from './config';
export const METHOD_SECTIONS = [
 ['understandable','Understandable',`At least ${T.minYears} annual periods, using up to ten years, few revenue declines or loss years, and stable operating margins. Banks need positive earnings in nine of ten years; insurers need eight. Their sector tests measure capital returns, book value plus dividends, share dilution and accounting warnings.`],
 ['moat','Moat',`Operating companies need a median return on invested capital of at least ${T.moat.roicMedian*100}%. ROIC divides after-tax operating profit by invested capital. Years with nonpositive invested capital use equity plus debt and leases. Positive earnings with no positive capital base are represented as above 100%. Banks use return on tangible common equity. Property and casualty insurers use their underwriting record, or tangible common returns when that record cannot decide the test. Other insurers use return on common equity. Nonpositive common capital fails the financial quality test.`],
 ['economics','Economics','Owner earnings start with net income, add depreciation and amortisation, then subtract estimated maintenance capital spending and stock compensation. Valuation uses the five-year normalised window disclosed in the dossier; annual charts show individual fiscal years. These are different windows and are labelled accordingly. When depreciation detail is absent, the conservative cash-flow calculation deducts all capital spending.'],
 ['management','Management','Share counts, retained earnings and market value creation indicate how managers allocate capital. The $1 test compares market value gained with cumulative retained earnings. If the retained-dollar test cannot be computed, per-share earnings or financial-company book-value growth is measured between three-year endpoint medians.'],
 ['accounting','Accounting','Accruals compare accounting profit with operating cash flow relative to assets. Receivables, stock compensation, restructuring and acquisition events provide additional checks. Each test requires its core measures. Supporting checks apply where their inputs can be established.'],
 ['price','Price and value','Owner earnings are projected for ten years plus a terminal value, discounted at a required return 10% a year (or local 10-year bond + 4 points if higher), divided by diluted shares, with only cash above 2% of revenue added. Owner earnings are after interest, so debt is reflected in the risk discount and leverage flag rather than deducted again. Banks and insurers use tangible book value and a ten-year median return on tangible equity capped at 25%. Expected return is distributable earnings yield plus retained-earnings growth capped at 6%. Both the buy price and return hurdle must be met. Yields refresh daily and moves of 0.1 percentage point trigger revaluation. Implausible yields fall back to the 30-day median, or a documented country default if the series is broken; unavailable local yields leave value unavailable. Companies passing all five tests with median ROIC excluding goodwill at least 20%, median owner-earnings return on total capital including goodwill and acquired intangibles at least 15%, and a full positive decade of owner earnings per share use their own winsorised growth, capped at 12% and fading to 3% over ten years. The two return medians use the last ten fiscal years with at least eight valid observations. Investment holding companies use reported NAV per share with dividends reinvested over ten years; total-return CAGR is capped at 12% and divided by price / NAV. A buy requires price at or below 85% of NAV and expected return of at least 10%. Other operating businesses retain the conservative 8% growth cap. Terminal growth represents a separate mature-economy assumption and can exceed a depressed near-term growth rate; this assumption is explicit, not a forecast. Where a lower-rate scenario would approach perpetual growth, its rate adjustment is reduced to keep the scenario finite. If the central required return does not exceed perpetual growth, value is unavailable. Low, mid and high values are scenarios, not statistical confidence intervals. Equal scenarios are labelled together.'],
 ] as const;
export const METHOD_COPY = [
  `${VALUE_PRODUCT_NAME} assesses business quality from financial statements and filing evidence, then compares a conservative estimate of value with the market price. Each test stands on its own; there is no blended score.`,
  `The buy price is the central estimated value less a discount of ${Object.values(T.price.requiredMos).map(n=>`${n*100}%`).join(', ')}, depending on earnings stability. Durable compounders use 15%; elevated leverage can raise that to 35% or 50%. Price below mid but above the buy price is “Wait”. Next closest uses a linear distance from the buy price; lower is cheaper. Companies below that price must also meet the expected return hurdle to qualify for Buy now.`,
  `${VALUE_PRODUCT_NAME} is an independent GigaInvestors product. These numerical thresholds are inspired by principles Buffett and Munger describe, not rules endorsed by them. “Model cutoff” means this site’s chosen threshold. The $1 retained-earnings test follows his stated principle; other cutoffs are model choices.`,
  "Open data comes from EODHD, SEC EDGAR, Japan’s EDINET and European ESEF filings, supplemented by annual Yahoo fundamentals. The dossier links to the source filing. Reference prices derived from market capitalisation are identified separately from closes. Machine-read qualitative signals are informational. Extracted quotations are withheld without an explicit supporting-evidence classification.",
  "The site covers companies in the selected major stock-market indexes. Western markets and Show all markets both operate within that universe. History uses today’s index membership, not membership at the historical date, creating survivorship bias. History uses current restated data and the surviving covered universe; delisted and missing companies are not reconstructed. Returns exclude dividends, are not annualised, and overlapping yearly cohorts are not an investable portfolio. Debt, cyclicality and currency movements can materially alter outcomes.",
  "Estimates depend on assumptions and are not guarantees or investment advice.",
] as const;
export const METHOD_RULE_COPY = [
  `These are ${VALUE_PRODUCT_NAME}’s model choices inspired by principles Buffett and Munger describe. “Model cutoff” means our selected threshold, not an endorsement. Passing one measure does not pass the entire quality test; the evidence panel lists the other checks.`,
  "The $1 retained-profit test requires at least $1 of market value gained per $1 kept, over 7–10 years. Standard price discounts are 25%, 35% or 50%, increasing with earnings variability. Durable compounders also need a ten-year median owner-earnings return of at least 15% on total capital including goodwill and acquired intangibles, with at least eight valid observations. Their price discount is 15%; elevated leverage can raise the discount to 35% or 50%. Investment holdings use at least seven consecutive annual NAV observations, with dividends, and annualize returns over the actual six-to-ten-year interval. Their total-return CAGR is capped at 12%; a ten-year compounded NAV realization is discounted at 10%. A buy needs a 15% discount to both that value and reported NAV. Expected return is the IRR of the same cash flows at today’s price, for every valuation tier. Banks require positive earnings in at least 90% of the latest seven to ten annual observations, median tangible-common-equity return of 12%, and at most one year below 5%. Insurers require positive earnings in at least 80% of those observations; P&C underwriting must be profitable in 7 of 10 years when reported, with tangible returns as the fallback. Life insurers use a 10% median ROE. Both need 7% annualized book-plus-dividend compounding and ordinary share growth no higher than 2%, measured over at least seven consecutive annual capital observations. Their retained-profit test compares book creation with earnings kept after dividends and buybacks. Optional credit, efficiency and reserve evidence is shown when available; missing core evidence cannot establish a pass."
] as const;
