/** Our numeric cutoffs operationalise Buffett's principles; they are not quotations from him. */
const labels:Record<string,[string,string]> = {
 historyYears:['Years of financial history','A long record helps distinguish a durable business from a lucky year.'],
 revenueDeclines:['Years when sales shrank','Resilient demand makes future cash easier to estimate.'],
 lossYears:['Years when the business lost money','Repeated losses make future owner cash less dependable.'],
 opMarginCv:['How steady profit margins are','Predictable margins make future earnings easier to estimate. A sustained, loss-free improvement can pass even with high variation.'],
 roicMedian:['Return on the money invested in the business','High returns suggest a durable advantage and less cash needed to grow.'],
 roicSecondLowest:['Return on invested money in a bad year','A durable advantage should hold up even in a weak year.'],
 roeMedian:['Return on shareholders’ money','For banks and insurers, equity is the capital that supports their business.'],
 roeSecondLowest:['Return on shareholders’ money in a bad year','Financial businesses need to earn adequate returns through weak years too.'],
 grossMarginDrop:['How much profit per sale has fallen','Falling margins can signal weaker pricing power. A negative decline means margins improved.'],
 unlimitedYears:['Years earning profit with no net capital tied up','Cash and other deductions can exceed invested capital; a negative denominator is not a negative return.'],
 capexToRevenue:['Sales spent on buildings and equipment','Businesses that need little investment leave more cash for owners.'],
 oeToNi:['Cash the owners could take out, per $1 of profit','Reported profit matters only if it becomes cash after maintaining the business.'],
 roiic:['Return on new money invested','Growth creates value only if the extra investment earns enough.'],
 nwcToRevenueChange:['Change in cash tied up running the business','Rising stock and unpaid bills can consume cash; a negative change can release cash.'],
 nwcToRevenueEnd:['Sales tied up in stock and unpaid bills','Less cash tied up in daily operations leaves more for owners.'],
 nwcToRevenueTrend:['Yearly change in cash tied up in operations','A negative trend can be good: less cash is needed to support each sale.'],
 marketCapGain:['Market value gained','Money kept by managers should increase what the business is worth.'],
 retainedEarnings:['Profits kept in the business','Retaining profit makes sense only if managers can invest it well.'],
 retainedDollar:['Market value created per $1 kept in the business','Managers should create at least a dollar of value for every dollar they keep.'],
 shareCagr:['Yearly change in the number of shares, 10 years','Issuing shares dilutes each owner’s stake; a negative change means fewer shares, often from buybacks.'],
 nonAcquisitionShareCagr:['Ordinary dilution over 10 years','Excludes only a disclosed acquisition contribution measured on the same weighted-average share basis. Actual shares still determine value per share.'],
 nonAcquisitionShareCagr5:['Ordinary dilution over 5 years','Separates evidenced acquisition issuance from other dilution; per-share earnings still use all shares.'],
 shareCagr5:['Yearly change in the number of shares, 5 years','Fewer shares can increase each owner’s claim on future cash. Negative can be good.'],
 retainedStartFy:['First year in the retained-profit test','A multi-year view gives retained profits time to create value.'],
 retainedEndFy:['Last year in the retained-profit test','Matched endpoints keep the comparison consistent.'],
 buybackYieldSpearman:['Were more shares bought back in cheaper years?','Buybacks create more value when management pays less for each dollar of earnings.'],
 averageBuybackYield:['Cash earnings relative to the buyback price','A higher earnings yield means a cheaper repurchase price.'],
 buybackYears:['Years of share-buyback history','Several observations are needed to judge management’s timing.'],
 cumulativeNetIncome:['Total profits over 10 years','A full cycle gives a more useful view than one good year.'],
 roicFirst3Median:['Return on invested money, first 3 years','Compare earlier returns with later ones to see whether reinvestment paid off.'],
 roicLast3Median:['Return on invested money, last 3 years','Sustained returns suggest managers have protected the business’s advantage.'],
 buybackYieldCovariance:['Were buybacks larger when shares were cheap?','Price matters just as much when the company buys its own shares.'],
 debtFundedBuybacks:['Borrowed money used to buy back shares','Debt can make buybacks riskier even when per-share earnings rise.'],
 acquisitionSpend:['Money spent buying other businesses','Acquisitions should earn adequate returns, not merely make a company bigger.'],
 roicTrend:['Yearly change in return on invested money','Falling returns may signal a weakening business advantage.'],
 accruals:['Profits backed by cash','Cash makes profits more credible. A negative number is good here: operating cash exceeds reported profit.'],
 receivablesGrowthGap:['Are unpaid customer bills growing faster than sales?','Uncollected sales can make reported profit look better than the cash received.'],
 dsri:['Growth in unpaid bills relative to sales','A rising ratio can be a warning that sales are harder to collect.'],
 redFlags:['Accounting warning signs','Several warning signs together deserve closer examination of the filing.'],
 restructuringYears:['Years with reorganisation charges','Repeated one-off costs may really be normal business expenses.'],
 sbcToOcf:['Operating cash used to pay staff with shares','Share-based pay is a real cost to owners even though it is not paid in cash.'],
 goodwillIntangiblesToEquity:['Acquired and intangible assets relative to owners’ equity','A large balance can make book value less tangible and increase write-down risk.'],
 marginOfSafety:['Discount below estimated value','A safety discount leaves room for mistakes in the estimate.'],
 mos:['Discount below estimated value','A safety discount leaves room for mistakes in the estimate.'],
 priceToMid:['Price compared with estimated value','Even an excellent business can be a poor purchase at too high a price.'],
 normalized:['Typical annual cash available to owners','Smoothing unusually good or bad years makes the estimate more conservative.'],
 growth:['Expected yearly growth','Optimistic growth assumptions can make a stock appear cheaper than it is.'],
 discountRate:['Yearly return required by the model','Future money is worth less than money available today.'],
 terminalGrowth:['Growth after the first 10 years','A mature business cannot outgrow its economy forever.'],
 bondYield:['Return available on government bonds','The return on a safer alternative helps set the required return.'],
 equityBondYield:['Owner cash relative to the price paid','This puts the cash yield of a business beside a bond yield.'],
 netCash:['Cash left after paying debt','Cash adds to value; debt reduces what is left for owners.'],
 shares:['Shares dividing ownership of the business','More shares divide the same business value among more claims.'],
 low:['Cautious estimate per share','Different assumptions produce different values.'],
 mid:['Central estimate per share','The central scenario is an estimate, not a guaranteed sale price.'],
 high:['Optimistic estimate per share','A range makes uncertainty visible.'],
};
export function metricHelp(id:string,technical:string) {
 const [label,why]=labels[id]??[technical,'The measure helps assess durable earning power and the cash left for owners.'];
 return {label,technical,why,source:id==='retainedDollar'?"Source: Buffett’s $1 retained-earnings principle; our model compares market value gained with profits retained.":id==='dsri'?'Source: GigaInvestors’ chosen threshold for the receivables-to-sales index, used as one signal in our accounting checklist.':"Source: GigaInvestors’ published method, inspired by Buffett; numeric cutoffs are our model choices, not Buffett’s stated rules."};
}
